import 'dotenv/config'
import postgres from 'postgres'
import { drizzle } from 'drizzle-orm/postgres-js'
import * as schema from './schema'

const client = postgres(process.env.DATABASE_URL!)
const db = drizzle(client, { schema })

const USUARIOS = [
  { nombre: 'Angela Chamaya',   email: 'angela@footloose.pe',  rol: 'SUPERVISOR' as const },
  { nombre: 'Diego Ordinola',   email: 'diego@footloose.pe',   rol: 'AGENTE' as const },
  { nombre: 'Bryant Alata',     email: 'bryant@footloose.pe',  rol: 'AGENTE' as const },
  { nombre: 'Marcelo Rojas',    email: 'marcelo@footloose.pe', rol: 'AGENTE' as const },
  { nombre: 'Luis Navarro',     email: 'luis@footloose.pe',    rol: 'AGENTE' as const },
]

const PROVEEDORES = [
  {
    nombre: 'BITEL', telefonoSoporte: 'WhatsApp: Grupo Soporte_Bitel_Footloose',
    instruccionGeneral: 'Realizar descartes iniciales, enviar número de CID de la tienda afectada y evidencia de los equipos encendidos al grupo de WhatsApp de soporte.',
    niveles: [{ nivel: 1, nombreContacto: 'Soporte Bitel Footloose', email: 'soporte-bitel@footloose.pe', celular: 'Grupo WhatsApp', tiempoRespSev1: '4 horas' }],
  },
  {
    nombre: 'CLARO', telefonoSoporte: '080000800',
    instruccionGeneral: 'Generar reporte vía telefónica al 080000800 con RUC 20427799973. Realizar descartes junto al operador. Si se genera número de avería, reportar al correo de Yesenia Palomino copiando a infraestructura.ti@footloose.pe',
    niveles: [
      { nivel: 1, nombreContacto: 'Yesenia Palomino',    email: 'yesenia.palomino@claro.com.pe', celular: '080000800',  tiempoRespSev1: '4 horas' },
      { nivel: 2, nombreContacto: 'Yrina Miranda Costa', email: 'yrina.miranda@claro.com.pe',    celular: '997109281',  tiempoRespSev1: '4 horas' },
      { nivel: 3, nombreContacto: 'Diana Necochea Cueva',email: 'Diana.necochea@claro.com.pe',   celular: '997555655',  tiempoRespSev1: '4 horas' },
      { nivel: 4, nombreContacto: 'Sandro Belevan Quispe',email:'Sandro.belevan@claro.com.pe',  celular: '982516039',  tiempoRespSev1: '4 horas' },
    ],
  },
  {
    nombre: 'CONVERGIA', telefonoSoporte: '080071010 / +51 16401010', correoSoporte: 'soporte@convergia.com.pe',
    instruccionGeneral: 'Completar descartes iniciales, solicitar fotografía de los equipos y enviar correo al contacto con copia a infraestructura.ti@footloose.pe, detallando código de tienda afectada y descartes realizados.',
    niveles: [
      { nivel: 1, nombreContacto: 'Alfredo Pineda',      email: 'alfredo.pineda@convergia.io',      celular: '+51 980 532 333', tiempoRespSev1: '1 hora' },
      { nivel: 2, nombreContacto: 'Victor Rodriguez',    email: 'victor.rodriguez@convergia.io',    celular: '+51 908 841 718', tiempoRespSev1: '2 horas' },
      { nivel: 3, nombreContacto: 'Alejandro Gutierrez', email: 'alejandro.gutierrez@convergia.io', celular: '+51 16401076',    tiempoRespSev1: '3 horas' },
      { nivel: 4, nombreContacto: 'Kleiber Palomino',    email: 'kleiber.palomino@convergia.io',    celular: '+51 983 447 193', tiempoRespSev1: '4 horas' },
    ],
  },
  {
    nombre: 'ENTEL',
    instruccionGeneral: 'Escalar directamente a Infraestructura TI de Footloose. El agente NO escala directo a Entel — requiere contacto autorizado.',
    niveles: [{ nivel: 1, nombreContacto: 'Infraestructura TI Footloose', email: 'infraestructura.ti@footloose.pe', tiempoRespSev1: '2 horas' }],
  },
  {
    nombre: 'MOVISTAR', telefonoSoporte: 'WhatsApp 999949241',
    instruccionGeneral: 'Reportar vía WhatsApp al 999949241 con RUC 20427799973 y número de servicio de la tienda.',
    niveles: [{ nivel: 1, nombreContacto: 'Soporte Movistar', email: 'soporte@movistar.com.pe', celular: '999949241', tiempoRespSev1: '4 horas' }],
  },
  {
    nombre: 'GTD', correoSoporte: 'Clientes.gtdperu@grupogtd.com',
    instruccionGeneral: 'Reportar usando RUC 20427799973, copiar a infraestructura.ti@footloose.pe, describir el problema y adjuntar evidencia de los descartes realizados.',
    niveles: [{ nivel: 1, nombreContacto: 'GTD Peru Soporte', email: 'Clientes.gtdperu@grupogtd.com', tiempoRespSev1: '4 horas' }],
  },
  {
    nombre: 'OPTICAL NETWORKS', telefonoSoporte: '92912912 / 993451010', correoSoporte: 'operadores@optical.pe',
    instruccionGeneral: 'Reportar al Centro de Operaciones. N1: 1h, N2: 2h, N3: 4h.',
    niveles: [
      { nivel: 1, nombreContacto: 'Centro de Operaciones',       email: 'operadores@optical.pe', celular: '92912912',  tiempoRespSev1: '1 hora' },
      { nivel: 2, nombreContacto: 'Cesar Chuqui (Supervisor TAC)',email: 'cchuqui@optical.pe',   celular: '970357963', tiempoRespSev1: '2 horas' },
      { nivel: 3, nombreContacto: 'Susana Quiroz (Jefe TAC)',    email: 'squiroz@optical.pe',    celular: '981116382', tiempoRespSev1: '4 horas' },
      { nivel: 4, nombreContacto: 'Giuliana Garayar (Gerente)',  email: 'ggarayar@optical.pe',   celular: '950959295', tiempoRespSev1: '8 horas' },
    ],
  },
  {
    nombre: 'FIBERLUX', correoSoporte: 'noc@fiberlux.pe',
    instruccionGeneral: 'Reportar vía correo electrónico describiendo y adjuntando pruebas de los descartes realizados.',
    niveles: [{ nivel: 1, nombreContacto: 'NOC Fiberlux', email: 'noc@fiberlux.pe', tiempoRespSev1: '4 horas' }],
  },
  {
    nombre: 'DITSAC', telefonoSoporte: 'WhatsApp 935128120',
    instruccionGeneral: 'Reportar vía WhatsApp al número 935128120.',
    niveles: [{ nivel: 1, nombreContacto: 'Soporte DITSAC', email: 'soporte@ditsac.pe', celular: '935128120', tiempoRespSev1: '4 horas' }],
  },
  {
    nombre: 'FIBRA AMAZÓNICA', telefonoSoporte: 'WhatsApp 931388888',
    instruccionGeneral: 'Reportar vía WhatsApp al número 931388888.',
    niveles: [{ nivel: 1, nombreContacto: 'Soporte Fibra Amazónica', email: 'soporte@fibramazonica.pe', celular: '931388888', tiempoRespSev1: '4 horas' }],
  },
  {
    nombre: 'TELCONET', correoSoporte: 'soporte@telconet.ec',
    instruccionGeneral: 'Enviar correo con los datos de la tienda afectada a soporte@telconet.ec.',
    niveles: [{ nivel: 1, nombreContacto: 'Soporte Telconet', email: 'soporte@telconet.ec', tiempoRespSev1: '4 horas' }],
  },
  {
    nombre: 'GONET', telefonoSoporte: 'WhatsApp +593969727281',
    instruccionGeneral: 'Contactar vía WhatsApp al +593969727281.',
    niveles: [{ nivel: 1, nombreContacto: 'Soporte Gonet', email: 'soporte@gonet.ec', celular: '+593969727281', tiempoRespSev1: '4 horas' }],
  },
]

const INS_BITEL   = 'Realizar descartes iniciales, enviar número de CID de la tienda afectada y evidencia de los equipos encendidos'
const INS_CLARO   = 'Generar reporte vía telefónica. RUC 20427799973, realizando descartes junto al operador. Si se genera un número de avería, reportar al correo de Yesenia copiando a infraestructura.ti@footloose.pe'
const INS_CLARO_S = 'Generar reporte vía telefónica. RUC 20427799973, realizando descartes junto al operador.'
const INS_CONV    = 'Tras completar los descartes iniciales, solicitar una fotografía de los equipos y enviar un correo al contacto, con copia a infraestructura.ti@footloose.pe'
const INS_ENTEL   = 'Después de realizar los descartes iniciales, se debe escalar con Infra TI ya que se requiere ser contacto autorizado'
const INS_MOV     = 'Reportar vía WhatsApp con el RUC 20427799973 y número de servicio.'
const INS_GTD     = 'Reportar usando el RUC 20427799973 y copiar a infraestructura.ti@footloose.pe. describir el problema y adjuntar los descartes realizados.'
const INS_FIBLUX  = 'Vía correo electrónico describiendo y adjuntando pruebas de los descartes realizados.'
const INS_DITSAC  = 'Reportar vía WhatsApp al número 935128120'
const INS_AMAZO   = 'Reportar vía WhatsApp al número 931388888'

const CT_BITEL  = 'Grupo Soporte_Bitel_Footloose'
const CT_CLARO  = '(080000800) yesenia.palomino@claro.com.pe'
const CT_CONV   = 'soporte@convergia.com.pe'
const CT_ENTEL  = 'Escalar a infraestructura TI'
const CT_MOV    = 'Vía WhatsApp 999949241'
const CT_GTD    = 'Clientes.gtdperu@grupogtd.com'
const CT_FIBLUX = 'noc@fiberlux.pe'
const CT_DITSAC = 'Vía WhatsApp 935128120'
const CT_AMAZO  = 'Vía WhatsApp 931388888'

const TIENDAS_RAW = [
  { codigo:'T02', nombreCc:'Jr. De la Unión 553',          formato:'FOOTLOOSE', direccion:'Jr. De la Unión 553',                              distrito:'Cercado de Lima',       provincia:'Lima',      ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5469', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'A' as const },
  { codigo:'T04', nombreCc:'Av. Horacio Urteaga 1337',     formato:'FOOTLOOSE', direccion:'Av. Horacio Urteaga 1337',                          distrito:'Jesús María',           provincia:'Lima',      ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5437', tieneContingencia:false, costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'D' as const },
  { codigo:'T08', nombreCc:'Av. Arnaldo Márquez 1354',     formato:'FOOTLOOSE', direccion:'Av. Arnaldo Márquez 1354',                          distrito:'Jesús María',           provincia:'Lima',      ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5438', tieneContingencia:false, costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'D' as const },
  { codigo:'T10', nombreCc:'CC Mega Plaza',                formato:'FOOTLOOSE', direccion:'Av. Alfredo Mendiola 3698 Int 26 1er piso',          distrito:'Independencia',         provincia:'Lima',      ubicacion:'Lima',     proveedor:'CLARO',    tipoConexion:'FIBRA ÓPTICA', cidServicio:null,        tieneContingencia:true,  costoMensual:'779.5',  instruccionReporte:INS_CLARO,   contactoSoporte:CT_CLARO,  cluster:'A' as const },
  { codigo:'T12', nombreCc:'CC Cerro Colorado Arequipa',   formato:'FOOTLOOSE', direccion:'Av. Aviacion N° 602 Int L145',                      distrito:'Arequipa',              provincia:'Arequipa',  ubicacion:'Provincia',proveedor:'CLARO',    tipoConexion:'HFC',          cidServicio:'54700429',  tieneContingencia:false, costoMensual:'159.32', instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'D' as const },
  { codigo:'T14', nombreCc:'Av. Gamarra 727',              formato:'FOOTLOOSE', direccion:'Jr. Prolongacion Gamarra 727',                       distrito:'La Victoria',           provincia:'Lima',      ubicacion:'Lima',     proveedor:'CONVERGIA',tipoConexion:'FTTH',         cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'409',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'C' as const },
  { codigo:'T16', nombreCc:'Jr. De la Unión 716',          formato:'FOOTLOOSE', direccion:'Jr. De la Unión 716-718',                           distrito:'Cercado de Lima',       provincia:'Lima',      ubicacion:'Lima',     proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:'201141529', tieneContingencia:false, costoMensual:'89.7',   instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'D' as const },
  { codigo:'T18', nombreCc:'Jr. Huallaga 228',             formato:'FOOTLOOSE', direccion:'Jr. Huallaga 228',                                  distrito:'Cercado de Lima',       provincia:'Lima',      ubicacion:'Lima',     proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:'972182760', tieneContingencia:false, costoMensual:'89.7',   instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'D' as const },
  { codigo:'T20', nombreCc:'Calle Elías Aguirre 467 Chiclayo', formato:'FOOTLOOSE', direccion:'Calle Elías Aguirre 467',                       distrito:'Chiclayo',              provincia:'Chiclayo',  ubicacion:'Provincia',proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5439', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'B' as const },
  { codigo:'T25', nombreCc:'CC Plaza Lima Sur',            formato:'FOOTLOOSE', direccion:'Av. Paseo de la Republica S/N Tda 242-244-246 2do Nivel', distrito:'Chorrillos',      provincia:'Lima',      ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5458', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'C' as const },
  { codigo:'T28', nombreCc:'Jr. Ayacucho 450',             formato:'FOOTLOOSE', direccion:'Jr Ayacucho 450',                                   distrito:'Cercado de Lima',       provincia:'Lima',      ubicacion:'Lima',     proveedor:'CLARO',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'25571481',  tieneContingencia:true,  costoMensual:'380',    instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'D' as const },
  { codigo:'T29', nombreCc:'Calle Tacna 346 Piura',        formato:'FOOTLOOSE', direccion:'Calle Tacna 346',                                   distrito:'Piura',                 provincia:'Piura',     ubicacion:'Provincia',proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5421', tieneContingencia:false, costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'D' as const },
  { codigo:'T31', nombreCc:'Calle Elías Aguirre 466 Chiclayo', formato:'FOOTLOOSE', direccion:'Calle Elías Aguirre 466',                       distrito:'Chiclayo',              provincia:'Chiclayo',  ubicacion:'Provincia',proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5440', tieneContingencia:false, costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'C' as const },
  { codigo:'T32', nombreCc:'CC Real Plaza SMP',            formato:'FOOTLOOSE', direccion:'Av. Alfredo Mendiola 7042 Int LC 110-111',          distrito:'San Martin de Porres',  provincia:'Lima',      ubicacion:'Lima',     proveedor:'CONVERGIA',tipoConexion:'LTE',          cidServicio:'ID-TIENDA', tieneContingencia:false, costoMensual:'380',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'C' as const },
  { codigo:'T39', nombreCc:'CC Open Plaza Atocongo',       formato:'FOOTLOOSE', direccion:'Av. Circunvalacion 1803 Int 13',                    distrito:'San Juan de Miraflores',provincia:'Lima',      ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5422', tieneContingencia:false, costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'D' as const },
  { codigo:'T40', nombreCc:'CC Open Plaza Atocongo',       formato:'FOOTLOOSE', direccion:'Av. Circunvalacion 1803 Int 02',                    distrito:'San Juan de Miraflores',provincia:'Lima',      ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5423', tieneContingencia:false, costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'C' as const },
  { codigo:'T41', nombreCc:'CC Plaza del Sol Ica',         formato:'FOOTLOOSE', direccion:'Av. San Martín - Ayabaca S/N Int 216',              distrito:'Ica',                   provincia:'Ica',       ubicacion:'Provincia',proveedor:'CONVERGIA',tipoConexion:'LTE',          cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'380',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'B' as const },
  { codigo:'T42', nombreCc:'CC Real Plaza Huancayo',       formato:'FOOTLOOSE', direccion:'Av. Ferrocarril 1035 Int 222',                      distrito:'Huancayo',              provincia:'Huancayo',  ubicacion:'Provincia',proveedor:'CONVERGIA',tipoConexion:'HFC',          cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'380',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'B' as const },
  { codigo:'T43', nombreCc:'CC Plaza Norte',               formato:'FOOTLOOSE', direccion:'Av. Tomas Valle con Panamericana Norte S/N Int 110B',distrito:'Independencia',        provincia:'Lima',      ubicacion:'Lima',     proveedor:'CLARO',    tipoConexion:'FIBRA ÓPTICA', cidServicio:null,        tieneContingencia:true,  costoMensual:'779.5',  instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'A' as const },
  { codigo:'T46', nombreCc:'CC Real Plaza Cercado',        formato:'FOOTLOOSE', direccion:'Av. Inca Garcilazo de la Vega 1337 Int 1070',       distrito:'Cercado',               provincia:'Lima',      ubicacion:'Lima',     proveedor:'CONVERGIA',tipoConexion:'HFC',          cidServicio:'ID-TIENDA', tieneContingencia:false, costoMensual:'380',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'C' as const },
  { codigo:'T59', nombreCc:'Av. La Molina 864',            formato:'FOOTLOOSE', direccion:'Av La Molina 864',                                  distrito:'La Molina',             provincia:'Lima',      ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5442', tieneContingencia:false, costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'C' as const },
  { codigo:'T66', nombreCc:'Av. Gran Chimú 772 SJL',       formato:'FOOTLOOSE', direccion:'Av. Gran Chimú 772',                                distrito:'San Juan de Lurigancho',provincia:'Lima',      ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5444', tieneContingencia:false, costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'C' as const },
  { codigo:'T70', nombreCc:'Jr. De la Unión 400',          formato:'FOOTLOOSE', direccion:'Jr. De la Unión 400',                               distrito:'Cercado de Lima',       provincia:'Lima',      ubicacion:'Lima',     proveedor:'ENTEL',    tipoConexion:'RADIO ENLACE', cidServicio:'714-9442',  tieneContingencia:true,  costoMensual:'228.73', instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'A' as const },
  { codigo:'T71', nombreCc:'CC Open Plaza Piura',          formato:'FOOTLOOSE', direccion:'Urb. Miraflores Av. Andrés Avelino Cáceres 147 Int LC 89', distrito:'Piura',         provincia:'Piura',     ubicacion:'Provincia',proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:'977806622', tieneContingencia:false, costoMensual:'132',    instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'C' as const },
  { codigo:'T72', nombreCc:'CC Mega Plaza Chimbote',       formato:'FOOTLOOSE', direccion:'Lotizacion Parque Gran Chavin Mz B Lote 1-A Int L90',distrito:'Chimbote',            provincia:'Chimbote',  ubicacion:'Provincia',proveedor:'CONVERGIA',tipoConexion:'HFC',          cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'380',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'B' as const },
  { codigo:'T74', nombreCc:'CC Mega Plaza Chimbote',       formato:'FOOTLOOSE', direccion:'Lotizacion Parque Gran Chavin Mz B Lote 1-A Int L73',distrito:'Chimbote',            provincia:'Chimbote',  ubicacion:'Provincia',proveedor:'CLARO',    tipoConexion:'HFC',          cidServicio:'43609168',  tieneContingencia:true,  costoMensual:'159.32', instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'B' as const },
  { codigo:'T78', nombreCc:'Jr. Ayacucho 615 Trujillo',    formato:'FOOTLOOSE', direccion:'Jr. Ayacucho 615',                                  distrito:'Trujillo',              provincia:'Trujillo',  ubicacion:'Provincia',proveedor:'MOVISTAR', tipoConexion:'FTTH',         cidServicio:'44305517',  tieneContingencia:true,  costoMensual:'106',    instruccionReporte:INS_MOV,     contactoSoporte:CT_MOV,    cluster:'B' as const },
  { codigo:'T79', nombreCc:'Av. Próceres de la Independencia 1711 SJL', formato:'FOOTLOOSE', direccion:'Av. Próceres de la Independencia 1711', distrito:'San Juan de Lurigancho',provincia:'Lima',    ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5445', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'A' as const },
  { codigo:'T81', nombreCc:'Mall Aventura Sta Anita',      formato:'FOOTLOOSE', direccion:'Av. Carretera Central 111 Tda b1045-1047',          distrito:'Santa Anita',           provincia:'Lima',      ubicacion:'Lima',     proveedor:'CLARO',    tipoConexion:'HFC',          cidServicio:'16769830',  tieneContingencia:true,  costoMensual:'87.29',  instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'D' as const },
  { codigo:'T83', nombreCc:'CC Real Plaza Juliaca',        formato:'FOOTLOOSE', direccion:'Jr. Tumbes S/N Int LC 151-153-155',                 distrito:'Juliaca',               provincia:'San Roman',  ubicacion:'Provincia',proveedor:'ENTEL',   tipoConexion:'LTE',          cidServicio:'923857535', tieneContingencia:false, costoMensual:'33.82',  instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'D' as const },
  { codigo:'T84', nombreCc:'CC Real Plaza Huánuco',        formato:'FOOTLOOSE', direccion:'Jr. Independencia S/N Int. LC-120/122',             distrito:'Huánuco',               provincia:'Huánuco',   ubicacion:'Provincia',proveedor:'CLARO',    tipoConexion:'HFC',          cidServicio:'62636165',  tieneContingencia:true,  costoMensual:'159.32', instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'B' as const },
  { codigo:'T85', nombreCc:'CC Real Plaza Piura',          formato:'FOOTLOOSE', direccion:'Av. Sánchez Cerro 234 LC 139',                      distrito:'Piura',                 provincia:'Piura',     ubicacion:'Provincia',proveedor:'CONVERGIA',tipoConexion:'LTE',          cidServicio:'ID-TIENDA', tieneContingencia:false, costoMensual:'380',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'B' as const },
  { codigo:'T87', nombreCc:'CC Real Plaza Sta. Clara',     formato:'FOOTLOOSE', direccion:'Av. Nicolas Ayllon 8694 Int 103B',                  distrito:'Ate Vitarte',           provincia:'Lima',      ubicacion:'Lima',     proveedor:'CONVERGIA',tipoConexion:'HFC',          cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'380',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'D' as const },
  { codigo:'T89', nombreCc:'CC Mega Plaza Cañete',         formato:'FOOTLOOSE', direccion:'Av. Mariscal Oscar Benavides S/N Int L-15 Lote 01', distrito:'Cañete',                provincia:'Cañete',    ubicacion:'Provincia',proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:'923832533', tieneContingencia:false, costoMensual:'89.7',   instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'C' as const },
  { codigo:'T90', nombreCc:'Mall Aventura Sta Anita',      formato:'FOOTLOOSE', direccion:'Av. Carretera Central 111 Tda B3009-B3011-B3005',   distrito:'Santa Anita',           provincia:'Lima',      ubicacion:'Lima',     proveedor:'CLARO',    tipoConexion:'HFC',          cidServicio:'16337561',  tieneContingencia:true,  costoMensual:'163.56', instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'C' as const },
  { codigo:'T91', nombreCc:'CC Real Plaza Cusco',          formato:'FOOTLOOSE', direccion:'Av. Collasuyo 2964, Cusco',                         distrito:'Cusco',                 provincia:'Cusco',     ubicacion:'Provincia',proveedor:'CLARO',    tipoConexion:'LTE',          cidServicio:'941461859', tieneContingencia:false, costoMensual:'42',     instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'D' as const },
  { codigo:'T92', nombreCc:'CC Real Plaza Chiclayo',       formato:'FOOTLOOSE', direccion:'Calle Mariscal Andrés Avelino Cáceres N°222 LC 164-165', distrito:'Chiclayo',        provincia:'Chiclayo',  ubicacion:'Provincia',proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5426', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'A' as const },
  { codigo:'T93', nombreCc:'CC Open Plaza Pucallpa',       formato:'FOOTLOOSE', direccion:'Av. Centenario Km 4.7 LC 11',                       distrito:'Pucallpa',              provincia:'Pucallpa',  ubicacion:'Provincia',proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5460', tieneContingencia:false, costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'B' as const },
  { codigo:'T95', nombreCc:'CC Real Plaza Cajamarca',      formato:'FOOTLOOSE', direccion:'Av. Vía de Evitamiento Norte S/N Barrio San Antonio LC 222-224-226', distrito:'Cajamarca', provincia:'Cajamarca',ubicacion:'Provincia',proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5474', tieneContingencia:true, costoMensual:'480',     instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'B' as const },
  { codigo:'T98', nombreCc:'CC Real Plaza Pucallpa',       formato:'FOOTLOOSE', direccion:'Av. Centenario N° 365 LC 102/104/106',               distrito:'Pucallpa',              provincia:'Pucallpa',  ubicacion:'Provincia',proveedor:'CLARO',    tipoConexion:'HFC',          cidServicio:'61634722',  tieneContingencia:false, costoMensual:'114.4',  instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'C' as const },
  { codigo:'TA2', nombreCc:'CC Open Plaza Huánuco',        formato:'FOOTLOOSE', direccion:'Lote 02,03 Y 04 Jr. Dos de mayo S/N - LC 10',       distrito:'Huánuco',               provincia:'Huánuco',   ubicacion:'Provincia',proveedor:'CLARO',    tipoConexion:'HFC',          cidServicio:'62636159',  tieneContingencia:false, costoMensual:'159.32', instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'C' as const },
  { codigo:'TA7', nombreCc:'Outlet Vulcano Ate',           formato:'FOOTLOOSE', direccion:'Calle Vulcano 176A',                                 distrito:'Ate Vitarte',           provincia:'Lima',      ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:null,        tieneContingencia:true,  costoMensual:null,     instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'C' as const },
  { codigo:'TA9', nombreCc:'CC Mega Plaza Chorrillos',     formato:'FOOTLOOSE', direccion:'Av. Alameda Sur esq. Con Av. San Marcos, mz II LC 108', distrito:'Chorrillos',       provincia:'Lima',      ubicacion:'Lima',     proveedor:'CONVERGIA',tipoConexion:'LTE',          cidServicio:'ID-TIENDA', tieneContingencia:false, costoMensual:'380',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'C' as const },
  { codigo:'TC1', nombreCc:'Mall del Sur SJM',             formato:'FOOTLOOSE', direccion:'Av. Los Lirios 301 Int 2170-2174',                   distrito:'San Juan de Miraflores',provincia:'Lima',      ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5461', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'A' as const },
  { codigo:'TC2', nombreCc:'Mall del Sur SJM',             formato:'FOOTLOOSE', direccion:'Av. Los Lirios 301 Int 1142',                        distrito:'San Juan de Miraflores',provincia:'Lima',      ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5462', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'C' as const },
  { codigo:'TC4', nombreCc:'CC Real Plaza Trujillo',       formato:'FOOTLOOSE', direccion:'Av. César Vallejo Oeste N°1345 esquina con Av. Fátima', distrito:'Trujillo',          provincia:'Trujillo',  ubicacion:'Provincia',proveedor:'CONVERGIA',tipoConexion:'LTE',          cidServicio:'ID-TIENDA', tieneContingencia:false, costoMensual:'380',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'D' as const },
  { codigo:'TC5', nombreCc:'CC Mega Plaza Jaén',           formato:'FOOTLOOSE', direccion:'Av. Mezones Muro S/N Int. 07-08-09',                 distrito:'Jaen',                  provincia:'Cajamarca', ubicacion:'Provincia',proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:'960212980', tieneContingencia:true,  costoMensual:'132',    instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'C' as const },
  { codigo:'TC6', nombreCc:'CC Plaza Norte',               formato:'TOP MODEL', direccion:'Av. Tomas Valle c/ Panamericana Norte S/N. Int. LI 110 A', distrito:'Independencia', provincia:'Lima',      ubicacion:'Lima',     proveedor:'CLARO',    tipoConexion:'FIBRA ÓPTICA', cidServicio:null,        tieneContingencia:true,  costoMensual:'779.5',  instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'A' as const },
  { codigo:'TC7', nombreCc:'CC Mega Plaza',                formato:'FOOTLOOSE', direccion:'Av. Alfredo Mendiola N° 3698 LC 309',                distrito:'Independencia',         provincia:'Lima',      ubicacion:'Lima',     proveedor:'CLARO',    tipoConexion:'FIBRA ÓPTICA', cidServicio:null,        tieneContingencia:true,  costoMensual:'779.5',  instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'A' as const },
  { codigo:'TC8', nombreCc:'CC Mega Plaza Pisco',          formato:'FOOTLOOSE', direccion:'Av. Las Américas Esq Av. Fermin Tanguis L14-L15',    distrito:'Pisco',                 provincia:'Ica',       ubicacion:'Provincia',proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:'923223342', tieneContingencia:true,  costoMensual:'132',    instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'A' as const },
  { codigo:'TC9', nombreCc:'CC Open Plaza Huancayo',       formato:'FOOTLOOSE', direccion:'Av. Ferrocarril N° 146 – 150 LC-29',                 distrito:'Huancayo',              provincia:'Huancayo',  ubicacion:'Provincia',proveedor:'MOVISTAR', tipoConexion:'ADSL',         cidServicio:'64413301',  tieneContingencia:false, costoMensual:'91.53',  instruccionReporte:INS_MOV,     contactoSoporte:CT_MOV,    cluster:'C' as const },
  { codigo:'TD1', nombreCc:'Av. Próceres de la Independencia SJL', formato:'FOOTLOOSE', direccion:'Av. Próceres de la Independencia N1720',     distrito:'San Juan de Lurigancho',provincia:'Lima',      ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5446', tieneContingencia:false, costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'D' as const },
  { codigo:'TD2', nombreCc:'CC El Quinde Ica',             formato:'FOOTLOOSE', direccion:'Av. Los Maestros N° 206 del Fundo San José Local 130,132,134', distrito:'Ica',         provincia:'Ica',       ubicacion:'Provincia',proveedor:'CONVERGIA',tipoConexion:'LTE',          cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'380',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'D' as const },
  { codigo:'TD3', nombreCc:'CC Miramar Ilo',               formato:'FOOTLOOSE', direccion:'Jirón Abtao No 623 -LC 11',                         distrito:'Ilo',                   provincia:'Moquegua',  ubicacion:'Provincia',proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5428', tieneContingencia:false, costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'D' as const },
  { codigo:'TD4', nombreCc:'CC Real Plaza La Curva VMT',   formato:'FOOTLOOSE', direccion:'Lote DEP del Pueblo Joven César Vallejo - LC 215',  distrito:'Villa Maria del Triunfo',provincia:'Lima',     ubicacion:'Lima',     proveedor:'CONVERGIA',tipoConexion:'HFC',          cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'380',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'C' as const },
  { codigo:'TD7', nombreCc:'Outlet Lurín',                 formato:'FOOTLOOSE', direccion:'Nro. s/n int.131 Otr.Predio las salinas (parcela c-41)', distrito:'Lurin',            provincia:'Lima',      ubicacion:'Lima',     proveedor:'CLARO',    tipoConexion:'FTTH',         cidServicio:'12332257',  tieneContingencia:false, costoMensual:'79',     instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'C' as const },
  { codigo:'TD8', nombreCc:'Calle Elias Aguirre 420 Chiclayo', formato:'FOOTLOOSE', direccion:'Calle Elias Aguirre 420',                       distrito:'Chiclayo',              provincia:'Chiclayo',  ubicacion:'Provincia',proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5447', tieneContingencia:false, costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'C' as const },
  { codigo:'TD9', nombreCc:'CC Costa Mar Tumbes',          formato:'FOOTLOOSE', direccion:'Calle San Martin N° 275 LC 104/105',                distrito:'Tumbes',                provincia:'Tumbes',    ubicacion:'Provincia',proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5435', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'C' as const },
  { codigo:'TE3', nombreCc:'Plaza Center Placita VES',     formato:'FOOTLOOSE', direccion:'Urb. Parque Industrial del Cono Sur Mz. K3 Lote 1', distrito:'Villa El Salvador',     provincia:'Lima',      ubicacion:'Lima',     proveedor:'ENTEL',    tipoConexion:'RADIO ENLACE', cidServicio:'717-9073',  tieneContingencia:true,  costoMensual:'381.27', instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'B' as const },
  { codigo:'TE6', nombreCc:'CC El Quinde Cajamarca',       formato:'FOOTLOOSE', direccion:'Av. Rafael Hoyos Rubio c/ Jr. Sor Manuela Gil 151 - LE 101', distrito:'Cajamarca',   provincia:'Cajamarca', ubicacion:'Provincia',proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5429', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'B' as const },
  { codigo:'TE7', nombreCc:'CC Plaza San Miguel',          formato:'FOOTLOOSE', direccion:'Av. La Marina N° 2000-2100 C-125-126',               distrito:'San Miguel',            provincia:'Lima',      ubicacion:'Lima',     proveedor:'CONVERGIA',tipoConexion:'LTE',          cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'380',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'B' as const },
  { codigo:'TE8', nombreCc:'CC Minka Callao',              formato:'FOOTLOOSE', direccion:'Avenida Argentina 3093, Local P03-G02-L590',         distrito:'Callao',                provincia:'Callao',    ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5464', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'B' as const },
  { codigo:'TF2', nombreCc:'Av. Canto Grande SJL',         formato:'FOOTLOOSE', direccion:'Av. Canto Grande Mz H lote 19',                     distrito:'San Juan de Lurigancho',provincia:'Lima',      ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5448', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'D' as const },
  { codigo:'TF5', nombreCc:'CC Real Plaza Puruchuco',      formato:'FOOTLOOSE', direccion:'Av. Nicolas Ayllon N° 4770, LC-248- EX FUNDO VISTA ALEGRE, 2do PISO', distrito:'Ate Vitarte', provincia:'Lima', ubicacion:'Lima', proveedor:'CLARO', tipoConexion:'FTTH', cidServicio:'11085657', tieneContingencia:false, costoMensual:'270', instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO, cluster:'D' as const },
  { codigo:'TF6', nombreCc:'CC Real Plaza Puruchuco',      formato:'FOOTLOOSE', direccion:'Av. Nicolas Ayllon N° 4770, LC-157, LC-158 1ER PISO', distrito:'Ate Vitarte',         provincia:'Lima',      ubicacion:'Lima',     proveedor:'CLARO',    tipoConexion:'FTTH',         cidServicio:'11085660',  tieneContingencia:true,  costoMensual:'270',    instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'B' as const },
  { codigo:'TF7', nombreCc:'Mall Plaza Comas',             formato:'FOOTLOOSE', direccion:'Av Los Angeles, Comas 15314 int. b2008-2010',        distrito:'Comas',                 provincia:'Lima',      ubicacion:'Lima',     proveedor:'CONVERGIA',tipoConexion:'FTTH',         cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'380',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'B' as const },
  { codigo:'TF8', nombreCc:'Mall Plaza Comas',             formato:'FOOTLOOSE', direccion:'Av Los Angeles, Comas 15315 int. B1009',             distrito:'Comas',                 provincia:'Lima',      ubicacion:'Lima',     proveedor:'CONVERGIA',tipoConexion:'FTTH',         cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'380',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'B' as const },
  { codigo:'TF9', nombreCc:'Plaza Vea Tumbes',             formato:'FOOTLOOSE', direccion:'Av. Teniente Vásquez (Panamericana Norte) con Calle La Marina s/n', distrito:'Tumbes', provincia:'Tumbes',   ubicacion:'Provincia',proveedor:'CLARO',    tipoConexion:'LTE',          cidServicio:'913037873', tieneContingencia:true,  costoMensual:'110.08', instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'C' as const },
  { codigo:'TG2', nombreCc:'Mall Aventura Chiclayo',       formato:'FOOTLOOSE', direccion:'Mall Aventura Int. 1029-1031-1033 cruce de la Panamericana Norte y Circunvalación', distrito:'Chiclayo', provincia:'Chiclayo', ubicacion:'Provincia', proveedor:'GTD', tipoConexion:'FIBRA ÓPTICA', cidServicio:'NC21138', tieneContingencia:true, costoMensual:'420', instruccionReporte:INS_GTD, contactoSoporte:CT_GTD, cluster:'B' as const },
  { codigo:'TG3', nombreCc:'CC Plaza Vea Puente Piedra',   formato:'FOOTLOOSE', direccion:'Av. San Lorenzo Mz. A, Lt 01 Urb. Las Vegas int. LC 105', distrito:'Puente Piedra',   provincia:'Lima',      ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5430', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'A' as const },
  { codigo:'TG4', nombreCc:'CC Plaza Vea Puente Piedra',   formato:'FOOTLOOSE', direccion:'Av. San Lorenzo Mz. A, Lt 01 Urb. Las Vegas int. LC 104', distrito:'Puente Piedra',   provincia:'Lima',      ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5431', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'A' as const },
  { codigo:'TG5', nombreCc:'CC Plaza Vea Lurín',           formato:'FOOTLOOSE', direccion:'Urb. San Vicente S/N. Calle Antigua Panamericana Sur Parcela B-43 int. LC-110', distrito:'Lurin', provincia:'Lima', ubicacion:'Lima', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5432', tieneContingencia:true, costoMensual:'480', instruccionReporte:INS_BITEL, contactoSoporte:CT_BITEL, cluster:'B' as const },
  { codigo:'TG6', nombreCc:'CC In Outlet Premium Faucett', formato:'FOOTLOOSE', direccion:'Av. Elmer Faucett Nro. 3443 Int 134',                distrito:'Callao',                provincia:'Callao',    ubicacion:'Lima',     proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:'923217912', tieneContingencia:true,  costoMensual:'132',    instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'B' as const },
  { codigo:'TG8', nombreCc:'CC Plaza Center Ventanilla',   formato:'FOOTLOOSE', direccion:'Av. Nestor Gambeta S/N Int 203',                    distrito:'Ventanilla',            provincia:'Callao',    ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5467', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'C' as const },
  { codigo:'TH1', nombreCc:'Av. Proceres de la Independencia SJL', formato:'FOOTLOOSE', direccion:'Av. Proceres De La Independencia N 1637-1639 Urb Las Flores', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', proveedor:'CONVERGIA', tipoConexion:'FTTH', cidServicio:'ID-TIENDA', tieneContingencia:true, costoMensual:'409', instruccionReporte:INS_CONV, contactoSoporte:CT_CONV, cluster:'B' as const },
  { codigo:'TH2', nombreCc:'CC Real Plaza Cusco',          formato:'FOOTLOOSE', direccion:'Av. Collasuyo No 2964 tda LC-181',                  distrito:'Cusco',                 provincia:'Cusco',     ubicacion:'Provincia',proveedor:'CONVERGIA',tipoConexion:'LTE',          cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'380',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'B' as const },
  { codigo:'TH3', nombreCc:'CC Mega Plaza Chincha',        formato:'FOOTLOOSE', direccion:'Pro. Mariscal Benavides Nro. 1224 (Tda. L31)',      distrito:'Chincha',               provincia:'Ica',       ubicacion:'Provincia',proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:'977661960', tieneContingencia:true,  costoMensual:'89.7',   instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'C' as const },
  { codigo:'TH4', nombreCc:'CC Mega Plaza Huaral',         formato:'FOOTLOOSE', direccion:'Car. Carretera Huaral KM. 8 (L001)',                 distrito:'Huaral',                provincia:'Huaral',    ubicacion:'Provincia',proveedor:'CLARO',    tipoConexion:'LTE',          cidServicio:null,        tieneContingencia:true,  costoMensual:'110.08', instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'C' as const },
  { codigo:'TH5', nombreCc:'CC Mega Plaza Jaén',           formato:'FOOTLOOSE', direccion:'Lote. B-C Otr. Sub Lote B-C Sector Zanja Honda (L18)', distrito:'Jaen',              provincia:'Cajamarca', ubicacion:'Provincia',proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:'955439099', tieneContingencia:true,  costoMensual:'132',    instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'C' as const },
  { codigo:'TH6', nombreCc:'CC Plaza Center Tarapoto',     formato:'FOOTLOOSE', direccion:'Av. Salaverry Nro. 888 LCI 104',                    distrito:'Tarapoto',              provincia:'San Martin', ubicacion:'Provincia',proveedor:'ENTEL',   tipoConexion:'LTE',          cidServicio:'960308321', tieneContingencia:true,  costoMensual:'132',    instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'C' as const },
  { codigo:'TH7', nombreCc:'Jr. Gregorio Delgado Tarapoto',formato:'FOOTLOOSE', direccion:'Jr. Gregorio Delgado Nro. 158',                     distrito:'Tarapoto',              provincia:'San Martin', ubicacion:'Provincia',proveedor:'CONVERGIA',tipoConexion:'FTTH',         cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'409',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'D' as const },
  { codigo:'TH8', nombreCc:'Av. Enrique Palacio Sullana',  formato:'FOOTLOOSE', direccion:'Av. Enrique Palacio Nro. 112 Piura',                distrito:'Sullana',               provincia:'Piura',     ubicacion:'Provincia',proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5452', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'C' as const },
  { codigo:'TH9', nombreCc:'CC Tottus Jockey Plaza',       formato:'FOOTLOOSE', direccion:'Av. Javier Prado Este Nro. 4010 Urb. Fundo Monterrico Chico', distrito:'Surco',      provincia:'Lima',      ubicacion:'Lima',     proveedor:'CONVERGIA',tipoConexion:'FTTH',         cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'380',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'D' as const },
  { codigo:'TI1', nombreCc:'CC Tottus Sullana',            formato:'FOOTLOOSE', direccion:'Av. Panamericana Nro. 461 Urb. Santa Rosa (L04)',   distrito:'Sullana',               provincia:'Piura',     ubicacion:'Provincia',proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:'977769681', tieneContingencia:true,  costoMensual:'89.7',   instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'B' as const },
  { codigo:'TI2', nombreCc:'Jr. Prospero Iquitos',         formato:'FOOTLOOSE', direccion:'Jr. Prospero Nro. 374',                             distrito:'Iquitos',               provincia:'Maynas',    ubicacion:'Provincia',proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5472', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'D' as const },
  { codigo:'TI4', nombreCc:'Av. Proceres de la Independencia SJL', formato:'FOOTLOOSE', direccion:'Av. Proceres de la Independen Nro. 3358 (Mz. H Lt. 05)', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5453', tieneContingencia:true, costoMensual:'480', instruccionReporte:INS_BITEL, contactoSoporte:CT_BITEL, cluster:'C' as const },
  { codigo:'TI5', nombreCc:'CC Tottus Cusco',              formato:'FOOTLOOSE', direccion:'Pro. Av. De La Cultura Nro. 2219 Int. LC04',        distrito:'Cusco',                 provincia:'Cusco',     ubicacion:'Provincia',proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:'970721169', tieneContingencia:true,  costoMensual:'132',    instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'D' as const },
  { codigo:'TI6', nombreCc:'CC Plaza Vea Moquegua',        formato:'FOOTLOOSE', direccion:'Av. Circunvalacion Lote. 1B Int. L102',             distrito:'Mariscal Nieto',        provincia:'Moquegua',  ubicacion:'Provincia',proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:null,        tieneContingencia:true,  costoMensual:'39.9',   instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'D' as const },
  { codigo:'TI7', nombreCc:'CC Plaza Vea Chincha',         formato:'FOOTLOOSE', direccion:'Nro. S/N Int. L106 Otr. Oscar R. Benavides',        distrito:'Chincha',               provincia:'Ica',       ubicacion:'Provincia',proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:'970742854', tieneContingencia:true,  costoMensual:'132',    instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'D' as const },
  { codigo:'TI8', nombreCc:'CC Tottus Chepen',             formato:'FOOTLOOSE', direccion:'Car. Panamericana Km. 696 (LC-03 Y 04 CC Tottus Chepen)', distrito:'Chepen',          provincia:'Chepen',    ubicacion:'Provincia',proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:'960201920', tieneContingencia:true,  costoMensual:'132',    instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'C' as const },
  { codigo:'TI9', nombreCc:'Av. Muro SJL',                 formato:'FOOTLOOSE', direccion:'Av. Muro Nro. 104B (Mz.J1 Lt.1 F Mcal.Caceres Sector II)', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5454', tieneContingencia:true, costoMensual:'480', instruccionReporte:INS_BITEL, contactoSoporte:CT_BITEL, cluster:'B' as const },
  { codigo:'TJ1', nombreCc:'Av. Leon Velarde Madre de Dios',formato:'FOOTLOOSE', direccion:'Av. Leon Velarde Nro. 437 Madre De Dios',          distrito:'Puerto Maldonado',      provincia:'Tambopata', ubicacion:'Provincia',proveedor:'CONVERGIA',tipoConexion:'FTTH',         cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'409',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'C' as const },
  { codigo:'TJ3', nombreCc:'CC Mall Aventura Arequipa',    formato:'FOOTLOOSE', direccion:'Av. Porongoche Nro. 500 (A-2051)',                  distrito:'Paucarpata',            provincia:'Arequipa',  ubicacion:'Provincia',proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:'970991254', tieneContingencia:true,  costoMensual:'132',    instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'D' as const },
  { codigo:'TJ4', nombreCc:'CC Plaza Vea Paita',           formato:'FOOTLOOSE', direccion:'Av. Almirante Miguel Grau 514 (LCE-102 Y 103)',     distrito:'Paita',                 provincia:'Paita',     ubicacion:'Provincia',proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:'949731850', tieneContingencia:true,  costoMensual:'110.08', instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'C' as const },
  { codigo:'TJ5', nombreCc:'Jr. San Martin Moyobamba',     formato:'FOOTLOOSE', direccion:'Jr. San Martin Nro. 478 (Barrio De Belen)',         distrito:'Moyobamba',             provincia:'Moyobamba', ubicacion:'Provincia',proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5456', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'D' as const },
  { codigo:'TJ6', nombreCc:'CC Mega Plaza Barranca',       formato:'FOOTLOOSE', direccion:'Calle Castilla No. 370',                            distrito:'Barranca',              provincia:'Barranca',  ubicacion:'Provincia',proveedor:'CLARO',    tipoConexion:'LTE',          cidServicio:'871207794', tieneContingencia:true,  costoMensual:'83.81',  instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'C' as const },
  { codigo:'TJ8', nombreCc:'Jr. Jose Prato Tingo Maria',   formato:'FOOTLOOSE', direccion:'Jr. Jose Prato N° 366 - 370',                      distrito:'Rupa Rupa',             provincia:'Huanuco',   ubicacion:'Provincia',proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5434', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'C' as const },
  { codigo:'TK1', nombreCc:'Jr. 2 De Mayo Huanuco',        formato:'FOOTLOOSE', direccion:'Jr. 2 De Mayo N°991',                               distrito:'Huanuco',               provincia:'Huanuco',   ubicacion:'Provincia',proveedor:'MOVISTAR', tipoConexion:'FTTH',         cidServicio:'62289662',  tieneContingencia:true,  costoMensual:'110.08', instruccionReporte:INS_MOV,     contactoSoporte:CT_MOV,    cluster:'D' as const },
  { codigo:'TK2', nombreCc:'CC Plaza Center Rex SMP',      formato:'FOOTLOOSE', direccion:'Cal. Alfredo Mendiola Esq. Tom Nro. S/N (LCE-202)', distrito:'San Martin De Porres',  provincia:'Lima',      ubicacion:'Lima',     proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:'923875012', tieneContingencia:true,  costoMensual:'132',    instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'D' as const },
  { codigo:'TK5', nombreCc:'CC Plaza San Miguel',          formato:'FOOTLOOSE', direccion:'Av. La Marina 2000 - San Miguel / 2do Nivel/ Local 248-249', distrito:'San Miguel',  provincia:'Lima',      ubicacion:'Lima',     proveedor:'CLARO',    tipoConexion:'LTE',          cidServicio:'941653684', tieneContingencia:true,  costoMensual:'144',    instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'C' as const },
  { codigo:'TK6', nombreCc:'Jr. De la Unión 431 Cercado',  formato:'FOOTLOOSE', direccion:'Jr. De La Union Nro. 431',                          distrito:'Cercado de Lima',       provincia:'Lima',      ubicacion:'Lima',     proveedor:'MOVISTAR', tipoConexion:'HFC',          cidServicio:'13128699',  tieneContingencia:true,  costoMensual:'104.9',  instruccionReporte:INS_MOV,     contactoSoporte:CT_MOV,    cluster:'D' as const },
  { codigo:'TK7', nombreCc:'Av. Gran Chimu 851 SJL',       formato:'R18',       direccion:'Av. Gran Chimu Nro. 851',                           distrito:'San Juan de Lurigancho',provincia:'Lima',      ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5441', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'D' as const },
  { codigo:'TK8', nombreCc:'Av. Santiago Antunez de Mayolo Los Olivos', formato:'FOOTLOOSE', direccion:'Av. Santiago Antunez De Mayolo Nro. 1163', distrito:'Los Olivos',     provincia:'Lima',      ubicacion:'Lima',     proveedor:'FIBERLUX', tipoConexion:'FIBRA ÓPTICA', cidServicio:null,        tieneContingencia:true,  costoMensual:'380',    instruccionReporte:INS_FIBLUX,  contactoSoporte:CT_FIBLUX, cluster:'A' as const },
  { codigo:'TL1', nombreCc:'Ventanilla Puerta Calle',      formato:'FOOTLOOSE', direccion:'Mza. C5 Lote. 13 Urb. Ex Zona Comercial E Industrial De Ventanilla', distrito:'Ventanilla', provincia:'Callao', ubicacion:'Lima', proveedor:'CONVERGIA', tipoConexion:'FTTH', cidServicio:'ID-TIENDA', tieneContingencia:true, costoMensual:'380', instruccionReporte:INS_CONV, contactoSoporte:CT_CONV, cluster:'C' as const },
  { codigo:'TL2', nombreCc:'Jr. Tacna Pucallpa',           formato:'FOOTLOOSE', direccion:'Jr. Tacna Nro. 663',                                distrito:'Pucallpa',              provincia:'Ucayali',   ubicacion:'Provincia',proveedor:'CONVERGIA',tipoConexion:'FTTH',         cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'409',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'D' as const },
  { codigo:'TL3', nombreCc:'Mall Aventura Iquitos',        formato:'FOOTLOOSE', direccion:'Av. Jose Abelardo Quiñonez Lote Las Ninfas-2 Local N° B-1022', distrito:'Iquitos',  provincia:'Maynas',    ubicacion:'Provincia',proveedor:'FIBRA AMAZÓNICA', tipoConexion:'FIBRA ÓPTICA', cidServicio:null, tieneContingencia:true, costoMensual:'634.6', instruccionReporte:INS_AMAZO, contactoSoporte:CT_AMAZO, cluster:'D' as const },
  { codigo:'TL4', nombreCc:'Manzana C1 SJL',               formato:'FOOTLOOSE', direccion:'Manzana C1 Lote 25, Urbanizacion Los Pinos',        distrito:'San Juan de Lurigancho',provincia:'Lima',      ubicacion:'Lima',     proveedor:'CONVERGIA',tipoConexion:'FTTH',         cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'380',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'C' as const },
  { codigo:'TL5', nombreCc:'CC Minka Callao',              formato:'R18',       direccion:'Avenida Argentina 3093 - Local: P09-C03-L109-L110', distrito:'Callao',                provincia:'Callao',    ubicacion:'Lima',     proveedor:'CLARO',    tipoConexion:'LTE',          cidServicio:'969723731', tieneContingencia:true,  costoMensual:'76',     instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'C' as const },
  { codigo:'TL6', nombreCc:'Mall Aventura Iquitos',        formato:'R18',       direccion:'Av. José Abelardo Quiñonez Lote Las Ninfas-2 Local N° B-2014', distrito:'Iquitos',  provincia:'Maynas',    ubicacion:'Provincia',proveedor:'FIBRA AMAZÓNICA', tipoConexion:'FIBRA ÓPTICA', cidServicio:null, tieneContingencia:true, costoMensual:'634.6', instruccionReporte:INS_AMAZO, contactoSoporte:CT_AMAZO, cluster:'D' as const },
  { codigo:'TL8', nombreCc:'Mall Aventura SJL',            formato:'FOOTLOOSE', direccion:'Av. Lurigancho N°997-999, Urb.Zarate Industrial interior B-1020 B-1022 B-1024', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', proveedor:'DITSAC', tipoConexion:'ANTENA', cidServicio:null, tieneContingencia:true, costoMensual:'84.75', instruccionReporte:INS_DITSAC, contactoSoporte:CT_DITSAC, cluster:'A' as const },
  { codigo:'TL9', nombreCc:'Mall Aventura SJL',            formato:'FOOTLOOSE', direccion:'Av. Lurigancho N°997-999, Urb.Zarate Industrial interior B-2022 B-2024 B-2026', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', proveedor:'DITSAC', tipoConexion:'ANTENA', cidServicio:null, tieneContingencia:true, costoMensual:'84.75', instruccionReporte:INS_DITSAC, contactoSoporte:CT_DITSAC, cluster:'B' as const },
  { codigo:'TM1', nombreCc:'CC Minka Callao',              formato:'FOOTLOOSE', direccion:'Avenida Argentina 3093, Local P07-C03-L442',         distrito:'Callao',                provincia:'Callao',    ubicacion:'Lima',     proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:'CID: 5473', tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'B' as const },
  { codigo:'TM4', nombreCc:'Jr. Gregorio Delgado Tarapoto',formato:'R18',       direccion:'Jirón Gregorio Delgado N° 136, Ciudad De Tarapoto',  distrito:'Tarapoto',              provincia:'San Martin', ubicacion:'Provincia',proveedor:'CONVERGIA',tipoConexion:'FTTH',         cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'409',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'D' as const },
  { codigo:'TM7', nombreCc:'CC In Outlet Premium Faucett', formato:'R18',       direccion:'Av. Elmer Faucett N° 3443 - Calle Corparc N° 142 INT. LC L112', distrito:'Callao',  provincia:'Callao',    ubicacion:'Lima',     proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:'923799911', tieneContingencia:true,  costoMensual:'89.7',   instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'D' as const },
  { codigo:'TM8', nombreCc:'Av. Naranjal Los Olivos',      formato:'FOOTLOOSE', direccion:'Av. Naranjal 1447-1449 Urb, Parque Naranjal II Etapa Los Olivos', distrito:'Los Olivos', provincia:'Lima', ubicacion:'Lima', proveedor:'MOVISTAR', tipoConexion:'HFC', cidServicio:'744707447', tieneContingencia:true, costoMensual:'99.9', instruccionReporte:INS_MOV, contactoSoporte:CT_MOV, cluster:'C' as const },
  { codigo:'TM9', nombreCc:'Ventanilla Caceres',           formato:'FOOTLOOSE', direccion:'Av. Andrés Avelino Cáceres Mz. C8 LT. 17 - Zona Urbanización Ex. Zona Comercial de Ventanilla', distrito:'Ventanilla', provincia:'Lima', ubicacion:'Lima', proveedor:'CONVERGIA', tipoConexion:'FTTH', cidServicio:'ID-TIENDA', tieneContingencia:true, costoMensual:'409', instruccionReporte:INS_CONV, contactoSoporte:CT_CONV, cluster:'B' as const },
  { codigo:'TN1', nombreCc:'CC Open Plaza Atocongo SJM',   formato:'FOOTLOOSE', direccion:'Av. Circunvalación N° 1801 - LC-37 - SAN JUAN DE MIRAFLORES', distrito:'San Juan de Miraflores', provincia:'Lima', ubicacion:'Lima', proveedor:'CLARO', tipoConexion:'LTE', cidServicio:'941653554', tieneContingencia:true, costoMensual:'143.2', instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO, cluster:'C' as const },
  { codigo:'TN5', nombreCc:'CC Boulevard Punta Hermosa',   formato:'FOOTLOOSE', direccion:'Interior Parcela 2A, distrito de Punta Hermosa, LC 10-11', distrito:'Punta Hermosa',   provincia:'Lima',      ubicacion:'Lima',     proveedor:'CLARO',    tipoConexion:'LTE',          cidServicio:'966459246', tieneContingencia:true,  costoMensual:'143.2',  instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO,  cluster:'C' as const },
  { codigo:'TN6', nombreCc:'Av. Nicolas de Piérola Carabayllo', formato:'R18', direccion:'Avenida Nicolas de Piérola Mz. P Lt 11, Carabayllo', distrito:'Carabayllo',            provincia:'Lima',      ubicacion:'Lima',     proveedor:'CONVERGIA',tipoConexion:'FTTH',         cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'409',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'D' as const },
  { codigo:'TN7', nombreCc:'Av. Tupac Amaru Carabayllo',   formato:'FOOTLOOSE', direccion:'Avenida Tupac Amaru 3270, Carabayllo',               distrito:'Carabayllo',            provincia:'Lima',      ubicacion:'Lima',     proveedor:'CONVERGIA',tipoConexion:'FTTH',         cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'409',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'D' as const },
  { codigo:'TN8', nombreCc:'Av. Tupac Amaru Carabayllo Sport', formato:'FOOTLOOSE', direccion:'Avenida Tupac Amaru 3346, Carabayllo',           distrito:'Carabayllo',            provincia:'Lima',      ubicacion:'Lima',     proveedor:'CONVERGIA',tipoConexion:'FTTH',         cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'409',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'C' as const },
  { codigo:'TN9', nombreCc:'Urb. Huaquillay Comas',        formato:'FOOTLOOSE', direccion:'Avenida Victor Andres Belaunde Oeste N° 356, Mz E lote 27, Urb. Huaquillay 2da etapa', distrito:'Comas', provincia:'Lima', ubicacion:'Lima', proveedor:'CONVERGIA', tipoConexion:'FTTH', cidServicio:'ID-TIENDA', tieneContingencia:true, costoMensual:'409', instruccionReporte:INS_CONV, contactoSoporte:CT_CONV, cluster:'A' as const },
  { codigo:'TO1', nombreCc:'CC KM 40 Lurín',               formato:'FOOTLOOSE', direccion:'Agrupamiento de Familias Jahuay Sector A, Mz Y Lote N° 1-4, Lurín', distrito:'Lurin', provincia:'Lima',      ubicacion:'Lima',     proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:'923998674', tieneContingencia:true,  costoMensual:'89.7',   instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'C' as const },
  { codigo:'TO2', nombreCc:'CC Plaza del Sol Huacho',      formato:'FOOTLOOSE', direccion:'CC Plaza del Sol, Calle Colon 601 Int. Lc 288, 286 y 284, Huacho', distrito:'Huacho', provincia:'Lima',      ubicacion:'Lima',     proveedor:'CONVERGIA',tipoConexion:'LTE',          cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'409',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'B' as const },
  { codigo:'TO3', nombreCc:'Av. Naranjal Los Olivos R18',  formato:'R18',       direccion:'Av. Naranjal Nro. 1485 Urb. Parque Del Naranjal II Etapa Los Olivos', distrito:'Los Olivos', provincia:'Lima', ubicacion:'Lima', proveedor:'CONVERGIA', tipoConexion:'FTTH', cidServicio:'ID-TIENDA', tieneContingencia:true, costoMensual:'380', instruccionReporte:INS_CONV, contactoSoporte:CT_CONV, cluster:'B' as const },
  { codigo:'TO4', nombreCc:'Calle López de Zuñiga Chancay',formato:'FOOTLOOSE', direccion:'Calle López de Zuñiga N 212, distrito de Chancay',  distrito:'Chancay',               provincia:'Lima',      ubicacion:'Lima',     proveedor:'CONVERGIA',tipoConexion:'FTTH',         cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'409',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'D' as const },
  { codigo:'TO5', nombreCc:'Av. Abancay Cercado',          formato:'FOOTLOOSE SPORT', direccion:'Avenida Abancay N° 1000 y Avenida Abancay N° 1004, Lima', distrito:'Cercado de Lima', provincia:'Lima', ubicacion:'Lima', proveedor:'CLARO', tipoConexion:'LTE', cidServicio:null, tieneContingencia:true, costoMensual:'110.08', instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO, cluster:'D' as const },
  { codigo:'TO6', nombreCc:'CC Real Plaza Puruchuco Sport',formato:'FOOTLOOSE SPORT', direccion:'Avenida nicolas ayllon 4770 - LCI-101 PURUCHUCO (Dentro de Plaza Vea)', distrito:'Ate Vitarte', provincia:'Lima', ubicacion:'Lima', proveedor:'GTD', tipoConexion:'FIBRA ÓPTICA', cidServicio:'NC227200', tieneContingencia:true, costoMensual:'650', instruccionReporte:INS_GTD, contactoSoporte:CT_GTD, cluster:'D' as const },
  { codigo:'TO7', nombreCc:'CC Real Plaza Puruchuco R18',  formato:'R18',       direccion:'Av. Nicolas Ayllon 4770 - LC-206 PURUCHUCO',        distrito:'Ate Vitarte',           provincia:'Lima',      ubicacion:'Lima',     proveedor:'GTD',      tipoConexion:'FIBRA ÓPTICA', cidServicio:'NC227157',  tieneContingencia:true,  costoMensual:'650',    instruccionReporte:INS_GTD,     contactoSoporte:CT_GTD,    cluster:'C' as const },
  { codigo:'TO8', nombreCc:'Centro Cívico Talara',         formato:'FOOTLOOSE', direccion:'Centro Cívico 002209, Urb. Centro Cívico, Pariñas', distrito:'Pariñas',               provincia:'Talara',    ubicacion:'Provincia',proveedor:'CONVERGIA',tipoConexion:'FTTH',         cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'409',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'C' as const },
  { codigo:'TO9', nombreCc:'CC Mega Plaza Chorrillos',     formato:'R18',       direccion:'Av. Alameda Sur esq. con Av. San Marcos, Manzana II, CC. Mega Plaza Chorrillos L206-207', distrito:'Chorrillos', provincia:'Lima', ubicacion:'Lima', proveedor:'CLARO', tipoConexion:'LTE', cidServicio:'986707525', tieneContingencia:true, costoMensual:'143.2', instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO, cluster:'D' as const },
  { codigo:'TP1', nombreCc:'CC Plaza Center Tarapoto',     formato:'FOOTLOOSE', direccion:'Av. Salaverry 888, Tarapoto 22201, LC 105-106',     distrito:'Tarapoto',              provincia:'San Martin', ubicacion:'Provincia',proveedor:'GTD',      tipoConexion:'FIBRA ÓPTICA', cidServicio:'NC227207',  tieneContingencia:true,  costoMensual:'650',    instruccionReporte:INS_GTD,     contactoSoporte:CT_GTD,    cluster:'D' as const },
  { codigo:'TP2', nombreCc:'Av. El Muro SJL R18',          formato:'R18',       direccion:'Av. Muro N° 104 Mz. J-1, Lt. 1-F San Juan de Lurigancho', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', proveedor:'CONVERGIA', tipoConexion:'FTTH', cidServicio:'ID-TIENDA', tieneContingencia:true, costoMensual:'409', instruccionReporte:INS_CONV, contactoSoporte:CT_CONV, cluster:'D' as const },
  { codigo:'TP3', nombreCc:'CC Mega Plaza Barranca R18',   formato:'R18',       direccion:'Jr. Ramon Zavala N° 164-180 y Jr. Castilla N° 107, interior L-2', distrito:'Barranca', provincia:'Barranca', ubicacion:'Provincia', proveedor:'CLARO', tipoConexion:'LTE', cidServicio:null, tieneContingencia:true, costoMensual:'76', instruccionReporte:INS_CLARO_S, contactoSoporte:CT_CLARO, cluster:'C' as const },
  { codigo:'TP4', nombreCc:'CC Portal F Pizarro Trujillo', formato:'FOOTLOOSE', direccion:'Jr. Pizarro No 650-654-664-666, CC. Portal F Pizarro interior LC 203Y204', distrito:'Trujillo', provincia:'Trujillo', ubicacion:'Provincia', proveedor:'GTD', tipoConexion:'FIBRA ÓPTICA', cidServicio:'NC227118', tieneContingencia:true, costoMensual:'650', instruccionReporte:INS_GTD, contactoSoporte:CT_GTD, cluster:'B' as const },
  { codigo:'TP5', nombreCc:'CC Mall Aventura Arequipa',    formato:'FOOTLOOSE', direccion:'Av. Porongoche No. 500, Int. A-1105, Paucarpata, Arequipa', distrito:'Arequipa',    provincia:'Arequipa',  ubicacion:'Provincia',proveedor:'ENTEL',    tipoConexion:'LTE',          cidServicio:null,        tieneContingencia:true,  costoMensual:'89.7',   instruccionReporte:INS_ENTEL,   contactoSoporte:CT_ENTEL,  cluster:'B' as const },
  { codigo:'TP6', nombreCc:'CC Real Plaza Cayma Arequipa', formato:'FOOTLOOSE', direccion:'CC. Real Plaza Arequipa, Av. Ejercito No. 1009, interior LC 133, Cayma', distrito:'Cayma', provincia:'Arequipa', ubicacion:'Provincia', proveedor:'ENTEL', tipoConexion:'LTE', cidServicio:'955451063', tieneContingencia:true, costoMensual:'132', instruccionReporte:INS_ENTEL, contactoSoporte:CT_ENTEL, cluster:'D' as const },
  { codigo:'TP7', nombreCc:'Av. Próceres de la Independencia Lurigancho R18', formato:'R18', direccion:'Av. Próceres de la Independencia 1715, San Juan de Lurigancho', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', proveedor:'CONVERGIA', tipoConexion:'FTTH', cidServicio:'ID-TIENDA', tieneContingencia:true, costoMensual:'409', instruccionReporte:INS_CONV, contactoSoporte:CT_CONV, cluster:'D' as const },
  { codigo:'TP8', nombreCc:'Jr. 28 de Julio Ayacucho',     formato:'FOOTLOOSE', direccion:'Jr. 28 de Julio Nro. 200-202 Sector Cercado Ayacucho', distrito:'Ayacucho',           provincia:'Ayacucho',  ubicacion:'Provincia',proveedor:'BITEL',    tipoConexion:'FIBRA ÓPTICA', cidServicio:null,        tieneContingencia:true,  costoMensual:'480',    instruccionReporte:INS_BITEL,   contactoSoporte:CT_BITEL,  cluster:'B' as const },
  { codigo:'TP9', nombreCc:'CC Real Plaza Piura',          formato:'FOOTLOOSE', direccion:'Zona Industrial antigua Av. Sánchez Cerro Nro 234 R-04-4', distrito:'Piura',          provincia:'Piura',     ubicacion:'Provincia',proveedor:'CONVERGIA',tipoConexion:'LTE',          cidServicio:'ID-TIENDA', tieneContingencia:true,  costoMensual:'380',    instruccionReporte:INS_CONV,    contactoSoporte:CT_CONV,   cluster:'D' as const },
]

async function seed() {
  console.log('🌱 Iniciando seed completo...\n')

  // Reemplazar usuarios existentes
  try {
    await db.delete(schema.usuarios)
    console.log('✓ Usuarios anteriores eliminados')
  } catch {
    console.log('⚠ No se pudieron eliminar usuarios (pueden tener incidentes vinculados)')
  }
  for (const u of USUARIOS) {
    await db.insert(schema.usuarios).values(u as any).onConflictDoUpdate({
      target: schema.usuarios.email,
      set: { nombre: u.nombre, rol: u.rol },
    })
    console.log(`✓ Usuario: ${u.nombre} (${u.rol})`)
  }

  const provMap: Record<string, string> = {}
  for (const p of PROVEEDORES) {
    const [prov] = await db.insert(schema.proveedores).values({
      nombre: p.nombre,
      correoSoporte: (p as any).correoSoporte ?? null,
      telefonoSoporte: (p as any).telefonoSoporte ?? null,
      instruccionGeneral: p.instruccionGeneral,
    }).onConflictDoUpdate({
      target: schema.proveedores.nombre,
      set: { instruccionGeneral: p.instruccionGeneral },
    }).returning()
    provMap[p.nombre] = prov.id
    for (const n of p.niveles) {
      await db.insert(schema.nivelesEscalamiento).values({ proveedorId: prov.id, ...n }).onConflictDoNothing()
    }
    console.log(`✓ Proveedor: ${p.nombre} (${p.niveles.length} niveles)`)
  }

  console.log('\n🏪 Insertando tiendas...')
  let tiendasOk = 0
  for (const t of TIENDAS_RAW) {
    const proveedorId = provMap[t.proveedor] ?? null
    try {
      await db.insert(schema.tiendas).values({
        codigo: t.codigo,
        nombreCc: t.nombreCc,
        formato: t.formato,
        direccion: t.direccion,
        distrito: t.distrito,
        provincia: t.provincia,
        ubicacion: t.ubicacion,
        cluster: t.cluster,
        proveedorId,
        tipoConexion: t.tipoConexion,
        cidServicio: t.cidServicio,
        tieneContingencia: t.tieneContingencia,
        costoMensual: t.costoMensual,
        instruccionReporte: t.instruccionReporte,
        contactoSoporte: t.contactoSoporte,
      }).onConflictDoNothing()
      tiendasOk++
    } catch (e) {
      console.log(`⚠ Tienda ${t.codigo} omitida`)
    }
  }
  console.log(`✓ ${tiendasOk} tiendas insertadas`)
  console.log('\n✅ Seed completado exitosamente')
  await client.end()
}

seed().catch(e => { console.error(e); process.exit(1) })
