import 'dotenv/config'
import postgres from 'postgres'
import { drizzle } from 'drizzle-orm/postgres-js'
import * as schema from './schema'

const client = postgres(process.env.DATABASE_URL!, { ssl: 'require' })
const db = drizzle(client, { schema })

const INS_BITEL  = 'Despues de realizar los descartes iniciales, enviar el número de CID de la tienda afectada y la evidencia de los equipos encendidos'
const INS_CLARO  = 'Generar reporte vía telefónica. RUC 20427799973, realizando descartes junto al operador. Si se genera un número de avería, reportar al correo de Yesenia copiando a infraestructura.ti@footloose.pe'
const INS_CONV   = 'Tras completar los descartes iniciales, solicitar una fotografía de los equipos y enviar un correo al contacto, con copia a infraestructura.ti@footloose.pe, detallando el código de la tienda afectada y los descartes realizados.'
const INS_ENTEL  = 'Después de realizar los descartes iniciales, se debe escalar con Infra TI ya que se requiere ser contacto autorizado'
const INS_MOV    = 'Reportar vía WhatsApp con el RUC 20427799973 y número de servicio.'
const INS_GTD    = 'Reportar utilizando el RUC 20427799973 y copiar a infraestructura.ti@footloose.pe. Describir el problema y adjuntar los descartes realizados.'
const INS_FIBLUX = 'Vía correo electrónico describiendo y adjuntando pruebas de los descartes realizados.'
const INS_TELCO  = 'Enviar un correo con los datos de la tienda afectada, se deja el modelo en el escalamiento.'

type T = {
  codigo: string; formato: string; nombreCc: string; direccion: string
  distrito: string; provincia: string; ubicacion: string; cluster: string
  proveedor: string; tipoConexion: string; cid: string; contingencia: string
  costo: string; instruccion: string; supervisor: string; administrador: string
  telTienda: string; celAdmin: string; correo: string
}

const TIENDAS: T[] = [
  { codigo:'T02', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Jr. De la Unión 553', distrito:'Cercado de Lima', provincia:'Lima', ubicacion:'Lima', cluster:'A', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5469', contingencia:'SI', costo:'480', instruccion:INS_BITEL, supervisor:'YESSENIA GIULIANA CHORRES CASTRO', administrador:'JANET VERONICA CARBAJAL SALAS', telTienda:'01 427 9617', celAdmin:'926818185', correo:'t02@footloose.pe' },
  { codigo:'T04', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Av. Horacio Urteaga 1337', distrito:'Jesús María', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5437', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'JORGE JHONATAN VASQUEZ RAMOS', administrador:'VERENIZ DOMINGO VEGA', telTienda:'605-3447', celAdmin:'989114775', correo:'t04@footloose.pe' },
  { codigo:'T08', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Av. Arnaldo Márquez 1354', distrito:'Jesús María', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5438', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'JORGE JHONATAN VASQUEZ RAMOS', administrador:'VERENIZ DOMINGO VEGA', telTienda:'01 519 6537', celAdmin:'989114779', correo:'t08@footloose.pe' },
  { codigo:'T10', formato:'FOOTLOOSE', nombreCc:'CC Mega Plaza', direccion:'Av. Alfredo Mendiola 3698 Int 26 1er piso', distrito:'Independencia', provincia:'Lima', ubicacion:'Lima', cluster:'B', proveedor:'CLARO', tipoConexion:'FIBRA ÓPTICA', cid:'', contingencia:'SI', costo:'779.5', instruccion:INS_CLARO, supervisor:'INGRID VERONICA PACCO CHAVEZ', administrador:'ELDIS RIMAPA CHINGO', telTienda:'(01)5214842', celAdmin:'989114780', correo:'t10@footloose.pe' },
  { codigo:'T12', formato:'FOOTLOOSE', nombreCc:'CC Cerro Colorado Arequipa', direccion:'Av. Aviacion N° 602 Int L145', distrito:'Arequipa', provincia:'Arequipa', ubicacion:'Provincia', cluster:'D', proveedor:'CLARO', tipoConexion:'HFC', cid:'54700429', contingencia:'', costo:'159.32', instruccion:INS_CLARO, supervisor:'CARLOS RICARDO OPORTO MANSILLA', administrador:'ALICIA SARCCO TAPARA', telTienda:'(054)700-429', celAdmin:'991689537', correo:'t12@footloose.pe' },
  { codigo:'T14', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Av. Gamarra 727', distrito:'La Victoria', provincia:'Lima', ubicacion:'Lima', cluster:'A', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'409', instruccion:INS_CONV, supervisor:'ALEX EUSEBIO POVES ZUBIETA', administrador:'HERNAN CONSTANTINO FLORES BACA', telTienda:'01 324 1062', celAdmin:'926797104', correo:'t14@footloose.pe' },
  { codigo:'T16', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Jr. De la Unión 716-718', distrito:'Cercado de Lima', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'ENTEL', tipoConexion:'LTE', cid:'201141529', contingencia:'', costo:'89.7', instruccion:INS_ENTEL, supervisor:'YESSENIA GIULIANA CHORRES CASTRO', administrador:'MARITZA TRINIDAD SOLIS GOMEZ', telTienda:'01 412 9968', celAdmin:'989114785', correo:'t16@footloose.pe' },
  { codigo:'T18', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Jr. Huallaga 228', distrito:'Cercado de Lima', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'ENTEL', tipoConexion:'LTE', cid:'972182760', contingencia:'', costo:'89.7', instruccion:INS_ENTEL, supervisor:'YESSENIA GIULIANA CHORRES CASTRO', administrador:'SELMIRA SANDOVAL VALLES', telTienda:'01 426 5193', celAdmin:'989114787', correo:'t18@footloose.pe' },
  { codigo:'T20', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Calle Elías Aguirre 467', distrito:'Chiclayo', provincia:'Chiclayo', ubicacion:'Provincia', cluster:'B', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5439', contingencia:'SI', costo:'480', instruccion:INS_BITEL, supervisor:'GLADYS MONTALBAN CASTILLO', administrador:'MARTHA ELENA YOCTUN VALVERDE', telTienda:'(074)518992', celAdmin:'989114790', correo:'t20@footloose.pe' },
  { codigo:'T25', formato:'FOOTLOOSE', nombreCc:'CC Plaza Lima Sur', direccion:'Av. Paseo de la Republica S/N Tda 242-244-246 2do Nivel', distrito:'Chorrillos', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5458', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'EDITH JOHANNA ESCALANTE RAMOS', administrador:'CARLOS ALBERTO SULLCA HERRERA', telTienda:'', celAdmin:'989594754', correo:'T25@fooloose.pe' },
  { codigo:'T28', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Jr Ayacucho 450', distrito:'Cercado de Lima', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'CLARO', tipoConexion:'FIBRA ÓPTICA', cid:'25571481', contingencia:'', costo:'380', instruccion:INS_CLARO, supervisor:'YESSENIA GIULIANA CHORRES CASTRO', administrador:'NIKE DAVID MONTALVAN FENCO', telTienda:'01 428 2536', celAdmin:'989114795', correo:'t28@footloose.pe' },
  { codigo:'T29', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Calle Tacna 346', distrito:'Piura', provincia:'Piura', ubicacion:'Provincia', cluster:'D', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5421', contingencia:'SI', costo:'480', instruccion:INS_BITEL, supervisor:'GLADYS MONTALBAN CASTILLO', administrador:'FLOR MARIA CASTILLO GUAYANAY', telTienda:'073 308 233', celAdmin:'989114796', correo:'t29@footloose.pe' },
  { codigo:'T31', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Calle Elías Aguirre 466', distrito:'Chiclayo', provincia:'Chiclayo', ubicacion:'Provincia', cluster:'C', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5440', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'GLADYS MONTALBAN CASTILLO', administrador:'KAREN LISETH SANCHEZ BRAVO', telTienda:'(074)524726', celAdmin:'989114798', correo:'t31@footloose.pe' },
  { codigo:'T32', formato:'FOOTLOOSE', nombreCc:'CC Real Plaza', direccion:'Av. Alfredo Mendiola 7042 Int LC 110-111', distrito:'San Martin de Porres', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'CONVERGIA', tipoConexion:'LTE', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'INGRID VERONICA PACCO CHAVEZ', administrador:'SAIRA CECILIA SANCHEZ ROJAS', telTienda:'01 557 6335', celAdmin:'989114799', correo:'t32@footloose.pe' },
  { codigo:'T39', formato:'FOOTLOOSE', nombreCc:'C.C.Open Plaza Atocongo', direccion:'Av. Circunvalacion 1803 Int 13', distrito:'San Juan de Miraflores', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5422', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'EDITH JOHANNA ESCALANTE RAMOS', administrador:'CARLOS ALFONSO TUANAMA ISUIZA', telTienda:'01 276 6305', celAdmin:'967749607', correo:'t39@footloose.pe' },
  { codigo:'T40', formato:'FOOTLOOSE', nombreCc:'C.C.Open Plaza Atocongo', direccion:'Av. Circunvalacion 1803 Int 02', distrito:'San Juan de Miraflores', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5423', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'EDITH JOHANNA ESCALANTE RAMOS', administrador:'SILVIA ISABEL FERNANDEZ DAVILA SARCOS', telTienda:'01 450 1206', celAdmin:'989114794', correo:'t40@footloose.pe' },
  { codigo:'T41', formato:'FOOTLOOSE', nombreCc:'CC Plaza del Sol', direccion:'Av. San Martín - Ayabaca S/N Int 216', distrito:'Ica', provincia:'Ica', ubicacion:'Provincia', cluster:'B', proveedor:'CONVERGIA', tipoConexion:'LTE', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'JORGE JHONATAN VASQUEZ RAMOS', administrador:'EMERSON MOISES HERNANDEZ TOLEDO', telTienda:'056 216 243', celAdmin:'989114773', correo:'t41@footloose.pe' },
  { codigo:'T42', formato:'FOOTLOOSE', nombreCc:'CC Real Plaza', direccion:'Av. Ferrocarril 1035 Int 222', distrito:'Huancayo', provincia:'Huancayo', ubicacion:'Provincia', cluster:'B', proveedor:'CONVERGIA', tipoConexion:'HFC', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'JESLIA MICHEL AVILA ASIPALI', administrador:'LUCERO KAREN BALTAZAR ORELLANA', telTienda:'', celAdmin:'989003081', correo:'t42@footloose.pe' },
  { codigo:'T43', formato:'FOOTLOOSE', nombreCc:'CC Plaza Norte', direccion:'Av. Tomas Valle con Panamericana Norte S/N Int 110B', distrito:'Independencia', provincia:'Lima', ubicacion:'Lima', cluster:'A', proveedor:'CLARO', tipoConexion:'FIBRA ÓPTICA', cid:'', contingencia:'SI', costo:'779.5', instruccion:INS_CLARO, supervisor:'INGRID VERONICA PACCO CHAVEZ', administrador:'YSABEL CLARA GONZALES GENEBROSO', telTienda:'(01)228-3038', celAdmin:'972548940', correo:'t43@footloose.pe' },
  { codigo:'T46', formato:'FOOTLOOSE', nombreCc:'CC Real Plaza', direccion:'Av. Inca Garcilazo de la Vega 1337 Int 1070', distrito:'Cercado', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'CONVERGIA', tipoConexion:'HFC', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'YESSENIA GIULIANA CHORRES CASTRO', administrador:'ELVA LISSET SOTELO MEDINA', telTienda:'01 423 9243', celAdmin:'989594753', correo:'t46@footloose.pe' },
  { codigo:'T53', formato:'COCHERA', nombreCc:'Puerta Calle', direccion:'Jr Chota 778', distrito:'Cercado de Lima', provincia:'Lima', ubicacion:'Lima', cluster:'', proveedor:'ENTEL', tipoConexion:'LTE', cid:'923848762', contingencia:'', costo:'89.7', instruccion:INS_ENTEL, supervisor:'', administrador:'', telTienda:'', celAdmin:'', correo:'' },
  { codigo:'T57', formato:'FOOTLOOSE', nombreCc:'CC Plaza del Sol', direccion:'Calle Colon 601 Int 238', distrito:'Huacho', provincia:'Huacho', ubicacion:'Provincia', cluster:'C', proveedor:'CLARO', tipoConexion:'LTE', cid:'913037871', contingencia:'', costo:'110.08', instruccion:INS_CLARO, supervisor:'JUAN VICTOR PACHERRES PAIVA', administrador:'MARIA ISABEL TENA JARA', telTienda:'01 397 5836', celAdmin:'969337350', correo:'t57@footloose.pe' },
  { codigo:'T59', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Av La Molina 864', distrito:'La Molina', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5442', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'WILBER ERNESTO PAREDES AMESQUITA', administrador:'KATHERINE DANAE BACILIO LULICHAC', telTienda:'', celAdmin:'', correo:'' },
  { codigo:'T66', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Av. Gran Chimú 772', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5444', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'ALEX EUSEBIO POVES ZUBIETA', administrador:'JULIA ELENA VELIZ MAYTA', telTienda:'651-0619', celAdmin:'994716856', correo:'t66@footloose.pe' },
  { codigo:'T70', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Jr. De la Unión 400', distrito:'Cercado de Lima', provincia:'Lima', ubicacion:'Lima', cluster:'A', proveedor:'ENTEL', tipoConexion:'RADIO ENLACE', cid:'714-9442', contingencia:'SI', costo:'228.73', instruccion:INS_ENTEL, supervisor:'YESSENIA GIULIANA CHORRES CASTRO', administrador:'MANUEL DIOMEDES FLORES DIAZ', telTienda:'762-6388', celAdmin:'913061234', correo:'t70@footloose.pe' },
  { codigo:'T71', formato:'FOOTLOOSE', nombreCc:'CC Open Plaza', direccion:'Urb. Miraflores Av. Andrés Avelino Cáceres 147 Int LC 89', distrito:'Piura', provincia:'Piura', ubicacion:'Provincia', cluster:'C', proveedor:'ENTEL', tipoConexion:'LTE', cid:'977806622', contingencia:'', costo:'132', instruccion:INS_ENTEL, supervisor:'GLADYS MONTALBAN CASTILLO', administrador:'GERARDO NUÑEZ MEJIA', telTienda:'073 344 304', celAdmin:'994717351', correo:'t71@footloose.pe' },
  { codigo:'T72', formato:'FOOTLOOSE', nombreCc:'CC Mega Plaza', direccion:'Lotizacion Parque Gran Chavin Mz B Lote 1-A Int L90', distrito:'Chimbote', provincia:'Chimbote', ubicacion:'Provincia', cluster:'B', proveedor:'CONVERGIA', tipoConexion:'HFC', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'JUAN VICTOR PACHERRES PAIVA', administrador:'ARACELI VANESSA DOWLING SANTA CRUZ', telTienda:'(043)609166', celAdmin:'968212783', correo:'t72@footloose.pe' },
  { codigo:'T74', formato:'FOOTLOOSE', nombreCc:'CC Mega Plaza', direccion:'Lotizacion Parque Gran Chavin Mz B Lote 1-A Int L73', distrito:'Chimbote', provincia:'Chimbote', ubicacion:'Provincia', cluster:'B', proveedor:'CLARO', tipoConexion:'HFC', cid:'43609168', contingencia:'SI', costo:'159.32', instruccion:INS_CLARO, supervisor:'JUAN VICTOR PACHERRES PAIVA', administrador:'ERICK XAVIER LLONTOP PISFIL', telTienda:'(043)609168', celAdmin:'968212784', correo:'t74@footloose.pe' },
  { codigo:'T78', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Jr. Ayacucho 615', distrito:'Trujillo', provincia:'Trujillo', ubicacion:'Provincia', cluster:'B', proveedor:'MOVISTAR', tipoConexion:'FTTH', cid:'44305517', contingencia:'', costo:'106', instruccion:INS_MOV, supervisor:'JUAN VICTOR PACHERRES PAIVA', administrador:'SANDRA PATRICIA GARCIA REYES', telTienda:'(044)250508', celAdmin:'968212786', correo:'t78@footloose.pe' },
  { codigo:'T79', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Av. Próceres de la Independencia 1711', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', cluster:'A', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5445', contingencia:'SI', costo:'480', instruccion:INS_BITEL, supervisor:'ALEX EUSEBIO POVES ZUBIETA', administrador:'MARIA DEL PILAR CHAVEZ VILLANUEVA', telTienda:'01 393 8300', celAdmin:'926838537', correo:'t79@footloose.pe' },
  { codigo:'T81', formato:'FOOTLOOSE', nombreCc:'Mall Aventura Sta Anita', direccion:'Av. Carretera Central 111 Tda b1045-1047', distrito:'Santa Anita', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'CLARO', tipoConexion:'HFC', cid:'16769830', contingencia:'', costo:'87.29', instruccion:INS_CLARO, supervisor:'JORGE JHONATAN VASQUEZ RAMOS', administrador:'ALISSON OFELIA APOLINARIO CHACA', telTienda:'(01)6769830', celAdmin:'926829839', correo:'t81@footloose.pe' },
  { codigo:'T83', formato:'FOOTLOOSE', nombreCc:'CC Real Plaza', direccion:'Jr. Tumbes S/N Int LC 151-153-155', distrito:'Juliaca', provincia:'San Roman', ubicacion:'Provincia', cluster:'C', proveedor:'ENTEL', tipoConexion:'LTE', cid:'923857535', contingencia:'', costo:'33.82', instruccion:INS_ENTEL, supervisor:'CARLOS RICARDO OPORTO MANSILLA', administrador:'MARITZA VILCA ARCE', telTienda:'051 322 748', celAdmin:'987954431', correo:'t83@footloose.pe' },
  { codigo:'T84', formato:'FOOTLOOSE', nombreCc:'CC Real Plaza', direccion:'Jr. Independencia S/N Int. LC-120/122', distrito:'Huánuco', provincia:'Huánuco', ubicacion:'Provincia', cluster:'B', proveedor:'CLARO', tipoConexion:'HFC', cid:'62636165', contingencia:'SI', costo:'159.32', instruccion:INS_CLARO, supervisor:'JESLIA MICHEL AVILA ASIPALI', administrador:'NURY VIVIANA SILVA ESTELA', telTienda:'(062)636165', celAdmin:'968212807', correo:'t84@footloose.pe' },
  { codigo:'T85', formato:'FOOTLOOSE', nombreCc:'CC Real Plaza', direccion:'Av. Sánchez Cerro 234 LC 139', distrito:'Piura', provincia:'Piura', ubicacion:'Provincia', cluster:'A', proveedor:'CONVERGIA', tipoConexion:'LTE', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'GLADYS MONTALBAN CASTILLO', administrador:'OMAR CARRASCO NEIRA', telTienda:'073 334 798', celAdmin:'994717191', correo:'t85@footloose.pe' },
  { codigo:'T87', formato:'FOOTLOOSE', nombreCc:'CC Real Plaza', direccion:'Av. Nicolas Ayllon 8694 Int 103B', distrito:'Ate Vitarte', provincia:'Lima', ubicacion:'Lima', cluster:'B', proveedor:'CONVERGIA', tipoConexion:'HFC', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'JORGE JHONATAN VASQUEZ RAMOS', administrador:'JUNIOR ALDAIR VERGARA LEON', telTienda:'01 356 3996', celAdmin:'994717060', correo:'t87@footloose.pe' },
  { codigo:'T89', formato:'FOOTLOOSE', nombreCc:'CC Mega Plaza', direccion:'Av. Mariscal Oscar Benavides S/N Int L-15 Lote 01', distrito:'Cañete', provincia:'Cañete', ubicacion:'Provincia', cluster:'C', proveedor:'ENTEL', tipoConexion:'LTE', cid:'923832533', contingencia:'', costo:'89.7', instruccion:INS_ENTEL, supervisor:'JORGE JHONATAN VASQUEZ RAMOS', administrador:'IVAN ISAAC YACTAYO REVILLA', telTienda:'01 581 2437', celAdmin:'987954468', correo:'t89@footloose.pe' },
  { codigo:'T90', formato:'FOOTLOOSE', nombreCc:'Mall Aventura Sta Anita', direccion:'Av. Carretera Central 111 Tda B3009-B3011-B3005', distrito:'Santa Anita', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'CLARO', tipoConexion:'HFC', cid:'16337561', contingencia:'', costo:'163.56', instruccion:INS_CLARO, supervisor:'JORGE JHONATAN VASQUEZ RAMOS', administrador:'ROXANA MABELY CARHUAJULCA SILVA', telTienda:'(01)6337561', celAdmin:'926828065', correo:'t90@footloose.pe' },
  { codigo:'T91', formato:'FOOTLOOSE', nombreCc:'CC Real Plaza', direccion:'Av. Collasuyo 2964, Cusco', distrito:'Cusco', provincia:'Cusco', ubicacion:'Provincia', cluster:'C', proveedor:'CLARO', tipoConexion:'LTE', cid:'941461859', contingencia:'', costo:'42', instruccion:INS_CLARO, supervisor:'CARLOS RICARDO OPORTO MANSILLA', administrador:'LUZGARDA TORRE CARPIO', telTienda:'084 243 161', celAdmin:'987954459', correo:'t91@footloose.pe' },
  { codigo:'T92', formato:'FOOTLOOSE', nombreCc:'CC Real Plaza', direccion:'Calle Mariscal Andrés Avelino Cáceres N°222 LC 164-165', distrito:'Chiclayo', provincia:'Chiclayo', ubicacion:'Provincia', cluster:'A', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5426', contingencia:'SI', costo:'480', instruccion:INS_BITEL, supervisor:'GLADYS MONTALBAN CASTILLO', administrador:'FLORILE FERNANDEZ FERNANDEZ', telTienda:'074 233 819', celAdmin:'989256361', correo:'t92@footloose.pe' },
  { codigo:'T93', formato:'FOOTLOOSE', nombreCc:'CC Open Plaza', direccion:'Av. Centenario Km 4.7 LC 11', distrito:'Pucallpa', provincia:'Pucallpa', ubicacion:'Provincia', cluster:'C', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5460', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'JESLIA MICHEL AVILA ASIPALI', administrador:'ERICKA DESSIRE PRADO VELA', telTienda:'(061) 634205', celAdmin:'989256368', correo:'t93@footloose.pe' },
  { codigo:'T95', formato:'FOOTLOOSE', nombreCc:'CC Real Plaza', direccion:'Av. Vía de Evitamiento Norte S/N Barrio San Antonio LC 222-224-226', distrito:'Cajamarca', provincia:'Cajamarca', ubicacion:'Provincia', cluster:'B', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5474', contingencia:'SI', costo:'480', instruccion:INS_BITEL, supervisor:'JUAN VICTOR PACHERRES PAIVA', administrador:'KAREN YOMIRA MURILLO CUSTODIO', telTienda:'076 367 496', celAdmin:'989256372', correo:'t95@footloose.pe' },
  { codigo:'T98', formato:'FOOTLOOSE', nombreCc:'CC Real Plaza', direccion:'Av. Centenario N° 365 LC 102/104/106', distrito:'Pucallpa', provincia:'Pucallpa', ubicacion:'Provincia', cluster:'C', proveedor:'CLARO', tipoConexion:'HFC', cid:'61634722', contingencia:'', costo:'114.4', instruccion:INS_CLARO, supervisor:'JESLIA MICHEL AVILA ASIPALI', administrador:'ERICKA DESSIRE PRADO VELA', telTienda:'(061) 634722', celAdmin:'989256458', correo:'t98@footloose.pe' },
  { codigo:'TA2', formato:'FOOTLOOSE', nombreCc:'CC Open Plaza', direccion:'Lote 02,03 Y 04 Jr. Dos de mayo S/N - LC 10', distrito:'Huánuco', provincia:'Huánuco', ubicacion:'Provincia', cluster:'C', proveedor:'CLARO', tipoConexion:'HFC', cid:'62636159', contingencia:'', costo:'159.32', instruccion:INS_CLARO, supervisor:'JESLIA MICHEL AVILA ASIPALI', administrador:'SOLEDAD ORTIZ PONCEANO', telTienda:'(062)636159', celAdmin:'989594748', correo:'ta2@footloose.pe' },
  { codigo:'TA7', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Calle Vulcano 176A', distrito:'Ate Vitarte', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'', contingencia:'', costo:'', instruccion:INS_BITEL, supervisor:'WILBER ERNESTO PAREDES AMESQUITA', administrador:'CLEIRE MARNY GONZALES MENDOZA', telTienda:'', celAdmin:'', correo:'' },
  { codigo:'TA9', formato:'FOOTLOOSE', nombreCc:'CC Mega Plaza', direccion:'Av. Alameda Sur esq. Con Av. San Marcos, mz II LC 108', distrito:'Chorrillos', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'CONVERGIA', tipoConexion:'LTE', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'EDITH JOHANNA ESCALANTE RAMOS', administrador:'RENATO PEDRO JOSE CESPEDES CASTILLO', telTienda:'', celAdmin:'', correo:'' },
  { codigo:'TC1', formato:'FOOTLOOSE', nombreCc:'Mall del Sur', direccion:'Av. Los Lirios 301 Int 2170-2174', distrito:'San Juan de Miraflores', provincia:'Lima', ubicacion:'Lima', cluster:'A', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5461', contingencia:'SI', costo:'480', instruccion:INS_BITEL, supervisor:'EDITH JOHANNA ESCALANTE RAMOS', administrador:'JHIAN CARLOS SALAS PISCO', telTienda:'(01)3759143', celAdmin:'968212809', correo:'tc1@footloose.pe' },
  { codigo:'TC2', formato:'FOOTLOOSE', nombreCc:'Mall del Sur', direccion:'Av. Los Lirios 301 Int 1142', distrito:'San Juan de Miraflores', provincia:'Lima', ubicacion:'Lima', cluster:'B', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'EDITH JOHANNA ESCALANTE RAMOS', administrador:'SILVIA ISABEL FERNANDEZ DAVILA SARCOS', telTienda:'(01)4785125', celAdmin:'994716591', correo:'tc2@footloose.pe' },
  { codigo:'TC4', formato:'FOOTLOOSE', nombreCc:'CC Real Plaza', direccion:'Av. César Vallejo Oeste N°1345 esquina con Av. Fátima', distrito:'Trujillo', provincia:'Trujillo', ubicacion:'Provincia', cluster:'', proveedor:'CONVERGIA', tipoConexion:'LTE', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'', administrador:'', telTienda:'', celAdmin:'', correo:'' },
  { codigo:'TC5', formato:'FOOTLOOSE', nombreCc:'CC Mega Plaza', direccion:'Av. Mezones Muro S/N Int. 07-08-09', distrito:'Jaen', provincia:'Cajamarca', ubicacion:'Provincia', cluster:'B', proveedor:'ENTEL', tipoConexion:'LTE', cid:'960212980', contingencia:'SI', costo:'132', instruccion:INS_ENTEL, supervisor:'JUAN VICTOR PACHERRES PAIVA', administrador:'ERACLIO EDICIO CHUMACERO MONDRAGON', telTienda:'', celAdmin:'969337339', correo:'tc5@footloose.pe' },
  { codigo:'TC6', formato:'FOOTLOOSE', nombreCc:'CC Plaza Norte', direccion:'Av. Tomas Valle c/ Panamericana Norte S/N. Int. LI 110 A', distrito:'Independencia', provincia:'Lima', ubicacion:'Lima', cluster:'A', proveedor:'CLARO', tipoConexion:'FIBRA ÓPTICA', cid:'', contingencia:'SI', costo:'779.5', instruccion:INS_CLARO, supervisor:'INGRID VERONICA PACCO CHAVEZ', administrador:'SHARON SORAYA VILLALOBOS GUEVARA', telTienda:'(01)3335325', celAdmin:'989114759', correo:'tc6@footloose.pe' },
  { codigo:'TC7', formato:'FOOTLOOSE', nombreCc:'CC Mega Plaza', direccion:'Av. Alfredo Mendiola N° 3698 LC 309', distrito:'Independencia', provincia:'Lima', ubicacion:'Lima', cluster:'A', proveedor:'CLARO', tipoConexion:'FIBRA ÓPTICA', cid:'', contingencia:'', costo:'779.5', instruccion:INS_CLARO, supervisor:'INGRID VERONICA PACCO CHAVEZ', administrador:'JANNELO HECTOR BERNAL VALDIVIA', telTienda:'', celAdmin:'933219517', correo:'tc7@footloose.pe' },
  { codigo:'TC8', formato:'FOOTLOOSE', nombreCc:'CC Mega Plaza', direccion:'Av. Las Américas Esq Av. Fermin Tanguis L14-L15', distrito:'Pisco', provincia:'Ica', ubicacion:'Provincia', cluster:'A', proveedor:'ENTEL', tipoConexion:'LTE', cid:'923223342', contingencia:'SI', costo:'132', instruccion:INS_ENTEL, supervisor:'JORGE JHONATAN VASQUEZ RAMOS', administrador:'JESSICA KARINA GALINDO TIPIAN', telTienda:'(056)385-087', celAdmin:'924482911', correo:'tc8@footloose.pe' },
  { codigo:'TC9', formato:'FOOTLOOSE', nombreCc:'CC Open Plaza', direccion:'Av. Ferrocarril N° 146-150 esq. con Prolongación San Carlos N° 136 LC-29', distrito:'Huancayo', provincia:'Huancayo', ubicacion:'Provincia', cluster:'C', proveedor:'MOVISTAR', tipoConexion:'ADSL', cid:'64413301', contingencia:'', costo:'91.53', instruccion:INS_MOV, supervisor:'JESLIA MICHEL AVILA ASIPALI', administrador:'ANGELITA PILAR GOZAR SANTOS', telTienda:'064-413301', celAdmin:'924482918', correo:'tc9@footloose.pe' },
  { codigo:'TD1', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Av. Próceres de la Independencia N1720', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5446', contingencia:'SI', costo:'480', instruccion:INS_BITEL, supervisor:'ALEX EUSEBIO POVES ZUBIETA', administrador:'KATIA TORRES MARINA', telTienda:'3864164', celAdmin:'960327544', correo:'td1@footloose.pe' },
  { codigo:'TD2', formato:'FOOTLOOSE', nombreCc:'CC El Quinde', direccion:'Av. Los Maestros N° 206 del Fundo San José Local 130,132,134', distrito:'Ica', provincia:'Ica', ubicacion:'Provincia', cluster:'B', proveedor:'CONVERGIA', tipoConexion:'LTE', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'JORGE JHONATAN VASQUEZ RAMOS', administrador:'CYNTHIA JESSENIA MUÑOA VILCARIMA', telTienda:'(056)386-237', celAdmin:'960328366', correo:'td2@footloose.pe' },
  { codigo:'TD3', formato:'FOOTLOOSE', nombreCc:'Centro Tematico', direccion:'Jirón Abtao No 623 -LC 11', distrito:'Ilo', provincia:'Moquegua', ubicacion:'Provincia', cluster:'C', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5428', contingencia:'SI', costo:'480', instruccion:INS_BITEL, supervisor:'CARLOS RICARDO OPORTO MANSILLA', administrador:'JULISSA JANE VERA BARRIOS', telTienda:'', celAdmin:'989114769', correo:'td3@footloose.pe' },
  { codigo:'TD4', formato:'FOOTLOOSE', nombreCc:'CC Real Plaza', direccion:'Lote DEP del Pueblo Joven César Vallejo - LC 215', distrito:'Villa Maria del Triunfo', provincia:'Lima', ubicacion:'Lima', cluster:'A', proveedor:'CONVERGIA', tipoConexion:'HFC', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'EDITH JOHANNA ESCALANTE RAMOS', administrador:'AUGUSTO ALBERTO DIAZ LEVANO', telTienda:'', celAdmin:'', correo:'' },
  { codigo:'TD7', formato:'FOOTLOOSE', nombreCc:'Outlet', direccion:'Nro. s/n int.131 Otr.Predio las salinas (parcela c-41)', distrito:'Lurin', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'CLARO', tipoConexion:'FTTH', cid:'12332257', contingencia:'', costo:'79', instruccion:INS_CLARO, supervisor:'EDITH JOHANNA ESCALANTE RAMOS', administrador:'MISHEL MAFFER CONTRERAS CARRASCO', telTienda:'(01)2332257', celAdmin:'933049060', correo:'td7@footloose.pe' },
  { codigo:'TD8', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Calle Elias Aguirre 420', distrito:'Chiclayo', provincia:'Chiclayo', ubicacion:'Provincia', cluster:'C', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5447', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'RUTH VASQUEZ VERGARA', administrador:'JENNIFER PEREZ CUSTODIO', telTienda:'(074)264699', celAdmin:'933050205', correo:'td8@footloose.pe' },
  { codigo:'TD9', formato:'FOOTLOOSE', nombreCc:'C.C. Costa Mar Plaza', direccion:'Calle San Martin N° 275 LC 104/105', distrito:'Tumbes', provincia:'Tumbes', ubicacion:'Provincia', cluster:'A', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5435', contingencia:'SI', costo:'480', instruccion:INS_BITEL, supervisor:'GLADYS MONTALBAN CASTILLO', administrador:'LYNETTE LESLEY ÑACCHA DUCHE', telTienda:'(072)280804', celAdmin:'960328746', correo:'td9@footloose.pe' },
  { codigo:'TE3', formato:'FOOTLOOSE', nombreCc:'Plaza Center Placita', direccion:'Urb. Parque Industrial del Cono Sur Mz. K3 Lote 1', distrito:'Villa El Salvador', provincia:'Lima', ubicacion:'Lima', cluster:'B', proveedor:'ENTEL', tipoConexion:'RADIO ENLACE', cid:'717-9073', contingencia:'', costo:'381.27', instruccion:INS_ENTEL, supervisor:'EDITH JOHANNA ESCALANTE RAMOS', administrador:'LUCERO ZANDY SANCHEZ PALOMINO', telTienda:'', celAdmin:'', correo:'' },
  { codigo:'TE6', formato:'FOOTLOOSE', nombreCc:'CC El Quinde', direccion:'Av. Rafael Hoyos Rubio c/ Jr. Sor Manuela Gil 151 - LE 101', distrito:'Cajamarca', provincia:'Cajamarca', ubicacion:'Provincia', cluster:'B', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5429', contingencia:'SI', costo:'480', instruccion:INS_BITEL, supervisor:'JUAN VICTOR PACHERRES PAIVA', administrador:'KAREN YOMIRA MURILLO CUSTODIO', telTienda:'', celAdmin:'969722239', correo:'te6@footloose.pe' },
  { codigo:'TE7', formato:'FOOTLOOSE', nombreCc:'CC Plaza San Miguel', direccion:'Av. La Marina N° 2000-2100 C-125-126', distrito:'San Miguel', provincia:'Lima', ubicacion:'Lima', cluster:'B', proveedor:'CONVERGIA', tipoConexion:'LTE', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'MITCHELL RAMIREZ ARBILDO', administrador:'RODRIGO ORLANDO PALOMINO MALPARTIDA', telTienda:'', celAdmin:'', correo:'' },
  { codigo:'TE8', formato:'FOOTLOOSE', nombreCc:'Minka', direccion:'Avenida Argentina 3093 - Local: P03-G02-L590', distrito:'Callao', provincia:'Callao', ubicacion:'Lima', cluster:'B', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5464', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'ANTONY KEVIN MORALES ARIAS', administrador:'DEVORA SUAREZ MARMOLEJO', telTienda:'468-6839', celAdmin:'946571222', correo:'te8@footloose.pe' },
  { codigo:'TEC01', formato:'FOOTLOOSE', nombreCc:'CC RIO CENTRO', direccion:'Av. Fco de Orellana Riocentro Norte local 117 planta alta.', distrito:'Guayaquil', provincia:'Ecuador', ubicacion:'Ecuador', cluster:'', proveedor:'TELCONET', tipoConexion:'FIBRA ÓPTICA', cid:'', contingencia:'', costo:'125', instruccion:INS_TELCO, supervisor:'', administrador:'', telTienda:'', celAdmin:'', correo:'' },
  { codigo:'TEC02', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Zona bancaria Mz. K20 calle Rocafuerte, Machala 070201', distrito:'Guayaquil', provincia:'Ecuador', ubicacion:'Ecuador', cluster:'', proveedor:'GONET', tipoConexion:'FTTH', cid:'', contingencia:'', costo:'77.63', instruccion:'', supervisor:'', administrador:'', telTienda:'', celAdmin:'', correo:'' },
  { codigo:'TEC03', formato:'FOOTLOOSE', nombreCc:'CC Gran Piazza', direccion:'Centro comercial Gran Piazza', distrito:'Machala', provincia:'Ecuador', ubicacion:'Ecuador', cluster:'', proveedor:'TELCONET', tipoConexion:'FIBRA ÓPTICA', cid:'', contingencia:'', costo:'125', instruccion:INS_TELCO, supervisor:'', administrador:'', telTienda:'', celAdmin:'', correo:'' },
  { codigo:'TEC04', formato:'R18', nombreCc:'CC Gran Piazza', direccion:'Centro comercial Gran Piazza', distrito:'Machala', provincia:'Ecuador', ubicacion:'Ecuador', cluster:'', proveedor:'TELCONET', tipoConexion:'FIBRA ÓPTICA', cid:'', contingencia:'', costo:'125', instruccion:INS_TELCO, supervisor:'', administrador:'', telTienda:'', celAdmin:'', correo:'' },
  { codigo:'TF2', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Av. Canto Grande Mz H lote 19', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5448', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'ALEX EUSEBIO POVES ZUBIETA', administrador:'TATIANA TORRES RENGIFO', telTienda:'', celAdmin:'913061226', correo:'tf2@footloose.pe' },
  { codigo:'TF5', formato:'FOOTLOOSE', nombreCc:'C.C. Real Plaza Puruchuco', direccion:'Av. Nicolas Ayllon N° 4770, LC-248, 2do PISO', distrito:'Ate Vitarte', provincia:'Lima', ubicacion:'Lima', cluster:'B', proveedor:'CLARO', tipoConexion:'FTTH', cid:'11085657', contingencia:'', costo:'270', instruccion:INS_CLARO, supervisor:'JORGE JHONATAN VASQUEZ RAMOS', administrador:'CARLA ESTRELLITA CISNEROS ROJAS', telTienda:'', celAdmin:'933044709', correo:'tf5@footloose.pe' },
  { codigo:'TF6', formato:'FOOTLOOSE', nombreCc:'C.C. Real Plaza Puruchuco', direccion:'Av. Nicolas Ayllon N° 4770, LC-157, LC-158, 1ER PISO', distrito:'Ate Vitarte', provincia:'Lima', ubicacion:'Lima', cluster:'B', proveedor:'CLARO', tipoConexion:'FTTH', cid:'11085660', contingencia:'SI', costo:'270', instruccion:INS_CLARO, supervisor:'JORGE JHONATAN VASQUEZ RAMOS', administrador:'GIOVANA CARRASCO PEÑA', telTienda:'', celAdmin:'989594759', correo:'tf6@footloose.pe' },
  { codigo:'TF7', formato:'FOOTLOOSE', nombreCc:'Mall Plaza Comas', direccion:'Av Los Angeles, Comas 15314 int. b2008-2010', distrito:'Comas', provincia:'Lima', ubicacion:'Lima', cluster:'B', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'INGRID VERONICA PACCO CHAVEZ', administrador:'LUZMILA ZARAY CORDOVA NORABUENA', telTienda:'01 3807071', celAdmin:'989256352', correo:'tf7@footloose.pe' },
  { codigo:'TF8', formato:'FOOTLOOSE', nombreCc:'Mall Plaza Comas', direccion:'Av Los Angeles, Comas 15315 int. B1009', distrito:'Comas', provincia:'Lima', ubicacion:'Lima', cluster:'B', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'INGRID VERONICA PACCO CHAVEZ', administrador:'OLGA MAGDALENA NEPONOCENO LABORIO', telTienda:'01 3807062', celAdmin:'989114810', correo:'tf8@footloose.pe' },
  { codigo:'TF9', formato:'FOOTLOOSE', nombreCc:'Plaza Vea Tumbes', direccion:'AV. Teniente Vásquez (Panamericana Norte) con Calle La Marina s/n', distrito:'Tumbes', provincia:'Tumbes', ubicacion:'Provincia', cluster:'C', proveedor:'CLARO', tipoConexion:'LTE', cid:'913037873', contingencia:'', costo:'110.08', instruccion:INS_CLARO, supervisor:'GLADYS MONTALBAN CASTILLO', administrador:'MELVA ALEJANDRA PRADO DEL ROSARIO', telTienda:'', celAdmin:'991840967', correo:'tf9@footloose.pe' },
  { codigo:'TG2', formato:'FOOTLOOSE', nombreCc:'Mall Aventura Chiclayo', direccion:'Mall Aventura Int. 1029-1031-1033 cruce Panamericana Norte y Circunvalación', distrito:'Chiclayo', provincia:'Chiclayo', ubicacion:'Provincia', cluster:'B', proveedor:'GTD', tipoConexion:'FIBRA ÓPTICA', cid:'NC21138', contingencia:'SI', costo:'420', instruccion:INS_GTD, supervisor:'GLADYS MONTALBAN CASTILLO', administrador:'JENNIFER ELIANA ANTON ORTIZ', telTienda:'074)743-0911', celAdmin:'994716625', correo:'tg2@footloose.pe' },
  { codigo:'TG3', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Av. San Lorenzo Mz. A, Lt 01 Urb. Las Vegas int. LC 105', distrito:'Puente Piedra', provincia:'Lima', ubicacion:'Lima', cluster:'A', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5430', contingencia:'SI', costo:'480', instruccion:INS_BITEL, supervisor:'MITCHELL RAMIREZ ARBILDO', administrador:'ELIZABETH LAOS RIMACHI', telTienda:'', celAdmin:'', correo:'' },
  { codigo:'TG4', formato:'FOOTLOOSE', nombreCc:'CC Plaza Vea Puente Piedra', direccion:'Av. San Lorenzo Mz. A, Lt 01 Urb. Las Vegas int. LC 104', distrito:'Puente Piedra', provincia:'Lima', ubicacion:'Lima', cluster:'A', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5431', contingencia:'SI', costo:'480', instruccion:INS_BITEL, supervisor:'MITCHELL RAMIREZ ARBILDO', administrador:'AMPARO DEL PILAR CABELLOS NUÑEZ', telTienda:'', celAdmin:'', correo:'' },
  { codigo:'TG5', formato:'FOOTLOOSE', nombreCc:'CC Plaza Vea Center Lurín', direccion:'Urb. San Vicente S/N. Calle Antigua Panamericana Sur Parcela B-43 int. LC-110', distrito:'Lurin', provincia:'Lima', ubicacion:'Lima', cluster:'B', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5432', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'ALEX EUSEBIO POVES ZUBIETA', administrador:'NAYSHA MARIBEL REYNAGA NESTARES', telTienda:'', celAdmin:'', correo:'' },
  { codigo:'TG6', formato:'FOOTLOOSE', nombreCc:'C.C. In Outlet Premium Faucett', direccion:'Av. Elmer Faucett Nro. 3443 Int 134', distrito:'Callao', provincia:'Callao', ubicacion:'Lima', cluster:'B', proveedor:'ENTEL', tipoConexion:'LTE', cid:'923217912', contingencia:'', costo:'132', instruccion:INS_ENTEL, supervisor:'MITCHELL RAMIREZ ARBILDO', administrador:'JOANNA MARIEL CURI BRAVO', telTienda:'(01)4926409', celAdmin:'989594763', correo:'tg6@footloose.pe' },
  { codigo:'TG8', formato:'FOOTLOOSE', nombreCc:'C.C. Plaza Center Ventanilla', direccion:'Av. Nestor Gambeta S/N Int 203', distrito:'Ventanilla', provincia:'Callao', ubicacion:'Lima', cluster:'C', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5467', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'MITCHELL RAMIREZ ARBILDO', administrador:'YESENIA MILAGROS VALDIVIA PALACIOS', telTienda:'', celAdmin:'955309697', correo:'tg8@footloose.pe' },
  { codigo:'TH1', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Av. Proceres De La Independencia N 1637-1639 Urb Las Flores', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', cluster:'B', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'409', instruccion:INS_CONV, supervisor:'ALEX EUSEBIO POVES ZUBIETA', administrador:'VICTOR FRANC CASTAÑEDA MANGO', telTienda:'627-8318', celAdmin:'969337345', correo:'th1@footloose.pe' },
  { codigo:'TH2', formato:'FOOTLOOSE', nombreCc:'CC Real Plaza Cusco', direccion:'Av. Collasuyo No 2964 tda LC-181', distrito:'Cusco', provincia:'Cusco', ubicacion:'Provincia', cluster:'B', proveedor:'CONVERGIA', tipoConexion:'LTE', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'CARLOS RICARDO OPORTO MANSILLA', administrador:'HIDA FIORELA DIAZ CCAICURI', telTienda:'', celAdmin:'913061210', correo:'th2@footloose.pe' },
  { codigo:'TH3', formato:'FOOTLOOSE', nombreCc:'C.C. Mega Plaza Chincha', direccion:'Pro. Mariscal Benavides Nro. 1224 (Tda. L31)', distrito:'Chincha', provincia:'Ica', ubicacion:'Provincia', cluster:'C', proveedor:'ENTEL', tipoConexion:'LTE', cid:'977661960', contingencia:'', costo:'89.7', instruccion:INS_ENTEL, supervisor:'JORGE JHONATAN VASQUEZ RAMOS', administrador:'MILAGROS YESENIA FUENTES MARTINEZ', telTienda:'', celAdmin:'994717241', correo:'th3@footloose.pe' },
  { codigo:'TH4', formato:'FOOTLOOSE', nombreCc:'CC Mega Plaza Huaral', direccion:'Car. Carretera Huaral Km. 8 (L001)', distrito:'Huaral', provincia:'Huaral', ubicacion:'Provincia', cluster:'C', proveedor:'CLARO', tipoConexion:'LTE', cid:'', contingencia:'', costo:'110.08', instruccion:INS_CLARO, supervisor:'JUAN VICTOR PACHERRES PAIVA', administrador:'GERALDINE MELANI ORENCIO ESPINOZA', telTienda:'', celAdmin:'947237225', correo:'th4@footloose.pe' },
  { codigo:'TH5', formato:'FOOTLOOSE', nombreCc:'CC Mega Plaza', direccion:'Lote. B-C Sector Zanja Honda (L18)', distrito:'Jaen', provincia:'Cajamarca', ubicacion:'Provincia', cluster:'C', proveedor:'ENTEL', tipoConexion:'LTE', cid:'955439099', contingencia:'', costo:'132', instruccion:INS_ENTEL, supervisor:'JUAN VICTOR PACHERRES PAIVA', administrador:'YOYNER RAMOS SILVA', telTienda:'', celAdmin:'947232864', correo:'th5@footloose.pe' },
  { codigo:'TH6', formato:'FOOTLOOSE', nombreCc:'CC Plaza Center Tarapoto', direccion:'Av. Salaverry Nro. 888 LCI 104', distrito:'Tarapoto', provincia:'San Martin', ubicacion:'Provincia', cluster:'C', proveedor:'ENTEL', tipoConexion:'LTE', cid:'960308321', contingencia:'', costo:'132', instruccion:INS_ENTEL, supervisor:'DIEGO JHONATAN SILVA MORI', administrador:'JOSE EDUAR PEREZ CHENTA', telTienda:'', celAdmin:'947235212', correo:'th6@footloose.pe' },
  { codigo:'TH7', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Jr. Gregorio Delgado Nro. 158', distrito:'Tarapoto', provincia:'San Martin', ubicacion:'Provincia', cluster:'B', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'409', instruccion:INS_CONV, supervisor:'DIEGO JHONATAN SILVA MORI', administrador:'JUAN CARLOS RUBIO ALTAMIRANO', telTienda:'', celAdmin:'947237884', correo:'th7@footloose.pe' },
  { codigo:'TH8', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Av. Enrique Palacio Nro. 112', distrito:'Sullana', provincia:'Piura', ubicacion:'Provincia', cluster:'C', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5452', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'GLADYS MONTALBAN CASTILLO', administrador:'WALDIR JAIR FLORES JUAREZ', telTienda:'073(559830)', celAdmin:'947238374', correo:'th8@footloose.pe' },
  { codigo:'TH9', formato:'FOOTLOOSE', nombreCc:'CC Tottus Jockey Plaza', direccion:'Av. Javier Prado Este Nro. 4010 Urb. Fundo Monterrico Chico', distrito:'Surco', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'WILBER ERNESTO PAREDES AMESQUITA', administrador:'JOEL LUIS ZELA GONZALES', telTienda:'', celAdmin:'', correo:'' },
  { codigo:'TI1', formato:'FOOTLOOSE', nombreCc:'CC Tottus Sullana', direccion:'Av. Panamericana Nro. 461 Urb. Santa Rosa (L04)', distrito:'Sullana', provincia:'Piura', ubicacion:'Provincia', cluster:'B', proveedor:'ENTEL', tipoConexion:'LTE', cid:'977769681', contingencia:'', costo:'89.7', instruccion:INS_ENTEL, supervisor:'GLADYS MONTALBAN CASTILLO', administrador:'WALDIR JAIR FLORES JUAREZ', telTienda:'', celAdmin:'972027565', correo:'ti1@footloose.pe' },
  { codigo:'TI2', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Jr. Prospero Nro. 374', distrito:'Iquitos', provincia:'Maynas', ubicacion:'Provincia', cluster:'D', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5472', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'DIEGO JHONATAN SILVA MORI', administrador:'MARIA NEYLI ROJAS ESPINOZA', telTienda:'', celAdmin:'955429752', correo:'' },
  { codigo:'TI4', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Av. Proceres de la Independencia Nro. 3358 (Mz. H Lt. 05)', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5453', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'ALEX EUSEBIO POVES ZUBIETA', administrador:'ANA ISABEL HUAMAN RUIZ', telTienda:'', celAdmin:'970136523', correo:'ti4@footloose.pe' },
  { codigo:'TI5', formato:'FOOTLOOSE', nombreCc:'CC. Tottus Cusco', direccion:'Av. De La Cultura Nro. 2219 Int. LC04', distrito:'Cusco', provincia:'Cusco', ubicacion:'Provincia', cluster:'D', proveedor:'ENTEL', tipoConexion:'LTE', cid:'970721169', contingencia:'', costo:'132', instruccion:INS_ENTEL, supervisor:'CARLOS RICARDO OPORTO MANSILLA', administrador:'YAMIRA MEJIA JIMENEZ', telTienda:'', celAdmin:'923686856', correo:'' },
  { codigo:'TI6', formato:'FOOTLOOSE', nombreCc:'CC Plaza Vea Moquegua', direccion:'Av. Circunvalacion Lote. 1B Int. L102', distrito:'Mariscal Nieto', provincia:'Moquegua', ubicacion:'Provincia', cluster:'D', proveedor:'ENTEL', tipoConexion:'LTE', cid:'', contingencia:'', costo:'39.9', instruccion:INS_ENTEL, supervisor:'CARLOS RICARDO OPORTO MANSILLA', administrador:'MANNY ROCIO MAMANI HANCCO', telTienda:'', celAdmin:'923961495', correo:'ti6@footloose.pe' },
  { codigo:'TI7', formato:'FOOTLOOSE', nombreCc:'CC Plaza Vea Chincha', direccion:'Nro. S/N Int. L106 Oscar R. Benavides (LCE)', distrito:'Chincha', provincia:'Ica', ubicacion:'Provincia', cluster:'D', proveedor:'ENTEL', tipoConexion:'LTE', cid:'970742854', contingencia:'', costo:'132', instruccion:INS_ENTEL, supervisor:'JORGE JHONATAN VASQUEZ RAMOS', administrador:'STEVEN ANTHONY LA PUENTE MATTOS', telTienda:'', celAdmin:'923960159', correo:'ti7@footloose.pe' },
  { codigo:'TI8', formato:'FOOTLOOSE', nombreCc:'CC Tottus Chepen', direccion:'Car. Panamericana Km. 696 (LC-03 Y 04 CC TOTTUS CHEPEN)', distrito:'Chepen', provincia:'Chepen', ubicacion:'Provincia', cluster:'C', proveedor:'ENTEL', tipoConexion:'LTE', cid:'960201920', contingencia:'', costo:'132', instruccion:INS_ENTEL, supervisor:'JUAN VICTOR PACHERRES PAIVA', administrador:'BREYSI THALIA VASQUEZ QUIROZ', telTienda:'', celAdmin:'960324234', correo:'' },
  { codigo:'TI9', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Av. Muro Nro. 104B (Mz.J1 Lt.1 F Mcal.Caceres Sector II)', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', cluster:'B', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5454', contingencia:'SI', costo:'480', instruccion:INS_BITEL, supervisor:'ALEX EUSEBIO POVES ZUBIETA', administrador:'MARIA MAGDALENA HILARIO BENANCIO', telTienda:'', celAdmin:'972027023', correo:'ti9@footloose.pe' },
  { codigo:'TJ1', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Av. Leon Velarde Nro. 437', distrito:'Puerto Maldonado', provincia:'Tambopata', ubicacion:'Provincia', cluster:'C', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'409', instruccion:INS_CONV, supervisor:'CARLOS RICARDO OPORTO MANSILLA', administrador:'ARNOL JIMENEZ SAAVEDRA', telTienda:'', celAdmin:'933186792', correo:'tj1@footloose.pe' },
  { codigo:'TJ3', formato:'FOOTLOOSE', nombreCc:'CC Mall Aventura', direccion:'Av. Porongoche Nro. 500 (A-2051)', distrito:'Paucarpata', provincia:'Arequipa', ubicacion:'Provincia', cluster:'C', proveedor:'ENTEL', tipoConexion:'LTE', cid:'970991254', contingencia:'', costo:'132', instruccion:INS_ENTEL, supervisor:'CARLOS RICARDO OPORTO MANSILLA', administrador:'LISSETH EMILY TICONA CALLENOVA', telTienda:'', celAdmin:'960215606', correo:'tj3@footloose.pe' },
  { codigo:'TJ4', formato:'FOOTLOOSE', nombreCc:'CC Plaza Vea Paita', direccion:'Av. Almirante Miguel Grau 514 (LCE-102 Y 103)', distrito:'Paita', provincia:'Paita', ubicacion:'Provincia', cluster:'C', proveedor:'ENTEL', tipoConexion:'LTE', cid:'949731850', contingencia:'', costo:'110.08', instruccion:INS_ENTEL, supervisor:'GLADYS MONTALBAN CASTILLO', administrador:'CARLOS ARMANDO CALDERON CENTURION', telTienda:'', celAdmin:'943881623', correo:'' },
  { codigo:'TJ5', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Jr. San Martin Nro. 478 (Barrio De Belen)', distrito:'Moyobamba', provincia:'Moyobamba', ubicacion:'Provincia', cluster:'D', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5456', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'DIEGO JHONATAN SILVA MORI', administrador:'MILENA LISBETH REYES VITE', telTienda:'', celAdmin:'989003082', correo:'tj5@footloose.pe' },
  { codigo:'TJ6', formato:'FOOTLOOSE', nombreCc:'CC Mega Plaza Barranca', direccion:'Calle Castilla No. 370', distrito:'Barranca', provincia:'Barranca', ubicacion:'Provincia', cluster:'B', proveedor:'CLARO', tipoConexion:'LTE', cid:'871207794', contingencia:'', costo:'83.81', instruccion:INS_CLARO, supervisor:'JUAN VICTOR PACHERRES PAIVA', administrador:'CATHERYN LUZ CERNA LLANQUE', telTienda:'', celAdmin:'943881281', correo:'tj6@footloose.pe' },
  { codigo:'TJ8', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Jr. Jose Prato N° 366 - 370', distrito:'Rupa Rupa', provincia:'Huanuco', ubicacion:'Provincia', cluster:'C', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5434', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'JESLIA MICHEL AVILA ASIPALI', administrador:'LUCILA ESTACIO CERVANTES', telTienda:'', celAdmin:'960208584', correo:'tj8@footloose.pe' },
  { codigo:'TK1', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Jr. 2 De Mayo N°991', distrito:'Huanuco', provincia:'Huanuco', ubicacion:'Provincia', cluster:'D', proveedor:'MOVISTAR', tipoConexion:'FTTH', cid:'62289662', contingencia:'', costo:'110.08', instruccion:INS_MOV, supervisor:'JESLIA MICHEL AVILA ASIPALI', administrador:'SHARON NELLY MARTEL RUBINA', telTienda:'', celAdmin:'951617982', correo:'tk1@footloose.pe' },
  { codigo:'TK2', formato:'FOOTLOOSE', nombreCc:'CC Plaza Center Rex', direccion:'Cal. Alfredo Mendiola Esq. Tom Nro. S/N (LCE-202)', distrito:'San Martin De Porres', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'ENTEL', tipoConexion:'LTE', cid:'923875012', contingencia:'', costo:'132', instruccion:INS_ENTEL, supervisor:'INGRID VERONICA PACCO CHAVEZ', administrador:'EVELYN ROCIO ALVAREZ MORENO', telTienda:'', celAdmin:'989114768', correo:'tk2@footloose.pe' },
  { codigo:'TK5', formato:'FOOTLOOSE', nombreCc:'CC Plaza San Miguel', direccion:'Av. La Marina 2000 - San Miguel / 2do Nivel / Local 248-249', distrito:'San Miguel', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'CLARO', tipoConexion:'LTE', cid:'941653684', contingencia:'', costo:'144', instruccion:INS_CLARO, supervisor:'MITCHELL RAMIREZ ARBILDO', administrador:'MELISSA GELEN VEGA RAMIREZ', telTienda:'', celAdmin:'933051436', correo:'tk5@footloose.pe' },
  { codigo:'TK6', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Jr. De La Union Nro. 431', distrito:'Cercado de Lima', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'MOVISTAR', tipoConexion:'HFC', cid:'13128699', contingencia:'', costo:'104.9', instruccion:INS_MOV, supervisor:'YESSENIA GIULIANA CHORRES CASTRO', administrador:'EDWIN DANIEL PEREZ GAMEZ', telTienda:'01 312 8699', celAdmin:'963650213', correo:'tk6@footloose.pe' },
  { codigo:'TK7', formato:'R18', nombreCc:'Puerta Calle', direccion:'Av. Gran Chimu Nro. 851', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5441', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'ALEX EUSEBIO POVES ZUBIETA', administrador:'RUTH CAMILA ZAVALA GONZALES', telTienda:'', celAdmin:'964571810', correo:'tk7@footloose.pe' },
  { codigo:'TK8', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Av. Santiago Antunez De Mayolo Nro. 1163', distrito:'Los Olivos', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'FIBERLUX', tipoConexion:'FIBRA ÓPTICA', cid:'', contingencia:'', costo:'380', instruccion:INS_FIBLUX, supervisor:'INGRID VERONICA PACCO CHAVEZ', administrador:'MARILU PARIATANTA DIAZ', telTienda:'01 3038251', celAdmin:'971807829', correo:'tk8@footloose.pe' },
  { codigo:'TL1', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Mza. C5 Lote. 13 Urb. Ex Zona Comercial de Ventanilla', distrito:'Ventanilla', provincia:'Callao', ubicacion:'Lima', cluster:'C', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'MITCHELL RAMIREZ ARBILDO', administrador:'YOYSI YANELY SANTOS PONCE', telTienda:'365-0929', celAdmin:'971135834', correo:'tl1@footloose.pe' },
  { codigo:'TL2', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Jr. Tacna Nro. 663', distrito:'Pucallpa', provincia:'Ucayali', ubicacion:'Provincia', cluster:'D', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'409', instruccion:INS_CONV, supervisor:'JESLIA MICHEL AVILA ASIPALI', administrador:'ROY TEDDY PACAYA PINCHI', telTienda:'061 634 203', celAdmin:'951617968', correo:'' },
  { codigo:'TL3', formato:'FOOTLOOSE', nombreCc:'Mall Aventura Iquitos', direccion:'Av. Jose Abelardo Quiñonez Lote Las Ninfas-2 Local N° B-1022', distrito:'Iquitos', provincia:'Maynas', ubicacion:'Provincia', cluster:'C', proveedor:'FIBRA AMAZONICA', tipoConexion:'FIBRA ÓPTICA', cid:'', contingencia:'', costo:'634.6', instruccion:'', supervisor:'DIEGO JHONATAN SILVA MORI', administrador:'MARCOS EDGAR TUANAMA VILCHEZ', telTienda:'', celAdmin:'943713679', correo:'' },
  { codigo:'TL4', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Manzana C1 Lote 25, Urbanizacion Los Pinos', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'ALEX EUSEBIO POVES ZUBIETA', administrador:'BAGNERT EULER QUISPE FERNANDEZ', telTienda:'', celAdmin:'905451843', correo:'' },
  { codigo:'TL5', formato:'R18', nombreCc:'Minka', direccion:'Avenida Argentina 3093 - Local: P09-C03-L109-L110', distrito:'Callao', provincia:'Callao', ubicacion:'Lima', cluster:'C', proveedor:'CLARO', tipoConexion:'LTE', cid:'969723731', contingencia:'', costo:'76', instruccion:INS_CLARO, supervisor:'MITCHELL RAMIREZ ARBILDO', administrador:'JHOSELIN BEATRIZ CUBA DIAZ', telTienda:'', celAdmin:'905459581', correo:'' },
  { codigo:'TL6', formato:'R18', nombreCc:'Mall Aventura Iquitos', direccion:'Av. José Abelardo Quiñonez, Lote Las Ninfas-2 Local N° B-2014', distrito:'Iquitos', provincia:'Maynas', ubicacion:'Provincia', cluster:'D', proveedor:'FIBRA AMAZONICA', tipoConexion:'FIBRA ÓPTICA', cid:'', contingencia:'', costo:'634.6', instruccion:'', supervisor:'DIEGO JHONATAN SILVA MORI', administrador:'XIOMY MELISSA LOPEZ EIZAGUIRRE', telTienda:'', celAdmin:'905459616', correo:'' },
  { codigo:'TL8', formato:'FOOTLOOSE', nombreCc:'Mall Aventura SJL', direccion:'Av. Lurigancho N°997-999, Urb. Zarate Industrial interior B-1020 B-1022 B-1024', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', cluster:'A', proveedor:'DITSAC', tipoConexion:'ANTENA', cid:'', contingencia:'SI', costo:'84.75', instruccion:'', supervisor:'ALEX EUSEBIO POVES ZUBIETA', administrador:'XIOMARA CRISTINA SANTILLAN MENDOZA', telTienda:'', celAdmin:'947238099', correo:'tl8@footloose.pe' },
  { codigo:'TL9', formato:'FOOTLOOSE-SPORT', nombreCc:'Mall Aventura SJL', direccion:'Av. Lurigancho N°997-999, Urb. Zarate Industrial interior B-2022 B-2024 B-2026', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', cluster:'B', proveedor:'DITSAC', tipoConexion:'ANTENA', cid:'', contingencia:'SI', costo:'84.75', instruccion:'', supervisor:'ALEX EUSEBIO POVES ZUBIETA', administrador:'MELANIE YANIS PERONE DELGADO', telTienda:'', celAdmin:'905436021', correo:'tl9@footloose.pe' },
  { codigo:'TM1', formato:'FOOTLOOSE', nombreCc:'Minka', direccion:'Avenida Argentina 3093, Local P07-C03-L442', distrito:'Callao', provincia:'Callao', ubicacion:'Lima', cluster:'B', proveedor:'BITEL', tipoConexion:'FIBRA ÓPTICA', cid:'CID: 5473', contingencia:'', costo:'480', instruccion:INS_BITEL, supervisor:'MITCHELL RAMIREZ ARBILDO', administrador:'JOHAN ALONSO BERMUDEZ CAUTI', telTienda:'', celAdmin:'961034284', correo:'tm1@footloose.pe' },
  { codigo:'TM4', formato:'R18', nombreCc:'Puerta Calle', direccion:'Jirón Gregorio Delgado N° 136, Ciudad De Tarapoto', distrito:'Tarapoto', provincia:'San Martin', ubicacion:'Provincia', cluster:'D', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'409', instruccion:INS_CONV, supervisor:'DIEGO JHONATAN SILVA MORI', administrador:'JUAN CARLOS RUBIO ALTAMIRANO', telTienda:'', celAdmin:'963651150', correo:'tm4@footloose.pe' },
  { codigo:'TM7', formato:'R18', nombreCc:'C.C. In Outlet Premium Faucett', direccion:'Av. Elmer Faucett N° 3443 - Calle Corparc N° 142 INT. LC L112', distrito:'Callao', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'ENTEL', tipoConexion:'LTE', cid:'923799911', contingencia:'', costo:'89.7', instruccion:INS_ENTEL, supervisor:'MITCHELL RAMIREZ ARBILDO', administrador:'JOANNA MARIEL CURI BRAVO', telTienda:'', celAdmin:'956655943', correo:'tm7@footloose.pe' },
  { codigo:'TM8', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Av. Naranjal 1447-1449 Urb. Parque Naranjal II Etapa Los Olivos', distrito:'Los Olivos', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'MOVISTAR', tipoConexion:'HFC', cid:'744707447', contingencia:'', costo:'99.9', instruccion:INS_MOV, supervisor:'INGRID VERONICA PACCO CHAVEZ', administrador:'VALLERI VILLAVICENCIO CAMPOS', telTienda:'', celAdmin:'955344159', correo:'tm8@footloose.pe' },
  { codigo:'TM9', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Av. Andrés Avelino Cáceres Mz. C8 LT. 17 - Zona Urbanización Ex. Zona Comercial de Ventanilla', distrito:'Ventanilla', provincia:'Lima', ubicacion:'Lima', cluster:'B', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'409', instruccion:INS_CONV, supervisor:'MITCHELL RAMIREZ ARBILDO', administrador:'GABRIELA DEL PILAR PALOMINO MERA', telTienda:'', celAdmin:'926836242', correo:'tm9@footloose.pe' },
  { codigo:'TN1', formato:'FOOTLOOSE', nombreCc:'C.C. Open Plaza Atocongo', direccion:'Av. Circunvalación N° 1801 - LC-37', distrito:'San Juan de Miraflores', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'CLARO', tipoConexion:'LTE', cid:'941653554', contingencia:'', costo:'143.2', instruccion:INS_CLARO, supervisor:'EDITH JOHANNA ESCALANTE RAMOS', administrador:'AMALIA POMA SANCHEZ', telTienda:'', celAdmin:'', correo:'' },
  { codigo:'TN5', formato:'FOOTLOOSE', nombreCc:'CC Boulevard Punta Hermosa', direccion:'Interior Parcela 2A, Punta Hermosa, LC 10-11', distrito:'Punta Hermosa', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'CLARO', tipoConexion:'LTE', cid:'966459246', contingencia:'', costo:'143.2', instruccion:INS_CLARO, supervisor:'EDITH JOHANNA ESCALANTE RAMOS', administrador:'SUSAN MABEL CASTILLO LIZANO', telTienda:'', celAdmin:'', correo:'' },
  { codigo:'TN6', formato:'R18', nombreCc:'Puerta Calle', direccion:'Avenida Nicolas de Piérola Mz. P Lt 11, Carabayllo', distrito:'Carabayllo', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'409', instruccion:INS_CONV, supervisor:'MITCHELL RAMIREZ ARBILDO', administrador:'RUTH MARISOL MAURICIO YACHI', telTienda:'905460013', celAdmin:'905460013', correo:'tn6@footloose.pe' },
  { codigo:'TN7', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Avenida Tupac Amaru 3270, Carabayllo', distrito:'Carabayllo', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'409', instruccion:INS_CONV, supervisor:'MITCHELL RAMIREZ ARBILDO', administrador:'DARWIN PAUL ZAPATA JIMENEZ', telTienda:'', celAdmin:'905451851', correo:'tn7@footloose.pe' },
  { codigo:'TN8', formato:'FOOTLOOSE-SPORT', nombreCc:'Puerta Calle', direccion:'Avenida Tupac Amaru 3346, Carabayllo', distrito:'Carabayllo', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'409', instruccion:INS_CONV, supervisor:'MITCHELL RAMIREZ ARBILDO', administrador:'KAROLL GERALDINE MORI ARELA', telTienda:'', celAdmin:'947235067', correo:'tn8@footloose.pe' },
  { codigo:'TN9', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Avenida Victor Andres Belaunde Oeste N° 356, Mz E lote 27, Urb. Huaquillay 2da etapa', distrito:'Comas', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'409', instruccion:INS_CONV, supervisor:'INGRID VERONICA PACCO CHAVEZ', administrador:'JUAN MIGUEL COLLQUE SANDOVAL', telTienda:'972028315', celAdmin:'972028315', correo:'tn9@footloose.pe' },
  { codigo:'TO1', formato:'FOOTLOOSE', nombreCc:'CC KM 40', direccion:'Agrupamiento de Familias Jahuay Sector A, Mz Y Lote N° 1-4, Lurín', distrito:'Lurin', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'ENTEL', tipoConexion:'LTE', cid:'923998674', contingencia:'', costo:'89.7', instruccion:INS_ENTEL, supervisor:'EDITH JOHANNA ESCALANTE RAMOS', administrador:'GINA ALEXANDRA PISCOYA ALARCON', telTienda:'', celAdmin:'920685234', correo:'TO1@fooloose.pe' },
  { codigo:'TO2', formato:'FOOTLOOSE', nombreCc:'CC Plaza del Sol', direccion:'Calle Colon 601 Int. Lc 288, 286 y 284', distrito:'Huacho', provincia:'Lima', ubicacion:'Lima', cluster:'B', proveedor:'CONVERGIA', tipoConexion:'LTE', cid:'ID-TIENDA', contingencia:'', costo:'409', instruccion:INS_CONV, supervisor:'JUAN VICTOR PACHERRES PAIVA', administrador:'DIANA NATHALY MEDINA EFFIO', telTienda:'', celAdmin:'960324149', correo:'to2@footloose.pe' },
  { codigo:'TO3', formato:'R18', nombreCc:'Puerta Calle', direccion:'Av. Naranjal Nro. 1485 Urb. Parque Del Naranjal II Etapa Los Olivos', distrito:'Los Olivos', provincia:'Lima', ubicacion:'Lima', cluster:'B', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'INGRID VERONICA PACCO CHAVEZ', administrador:'JESSICA NATALIA LA ROSA FLORES', telTienda:'', celAdmin:'989114774', correo:'to3@footloose.pe' },
  { codigo:'TO4', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Calle López de Zuñiga N 212, Chancay', distrito:'Chancay', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'409', instruccion:INS_CONV, supervisor:'JUAN VICTOR PACHERRES PAIVA', administrador:'LIZ VANESSA GOMEZ BLAS', telTienda:'948874606', celAdmin:'948874606', correo:'TO4@footloose.pe' },
  { codigo:'TO5', formato:'FOOTLOOSE SPORT', nombreCc:'Puerta Calle', direccion:'Avenida Abancay N° 1000 y Avenida Abancay N° 1004', distrito:'Cercado de Lima', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'CLARO', tipoConexion:'LTE', cid:'', contingencia:'', costo:'110.08', instruccion:INS_CLARO, supervisor:'YESSENIA GIULIANA CHORRES CASTRO', administrador:'EDELMIRA ROJAS MANCHAY', telTienda:'', celAdmin:'926808897', correo:'to5@footloose.pe' },
  { codigo:'TO6', formato:'FOOTLOOSE SPORT', nombreCc:'CC Real Plaza Puruchuco', direccion:'Avenida Nicolas Ayllon 4770 - LCI-101 PURUCHUCO', distrito:'Ate Vitarte', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'GTD', tipoConexion:'FIBRA ÓPTICA', cid:'NC227200', contingencia:'SI', costo:'650', instruccion:INS_GTD, supervisor:'JORGE JHONATAN VASQUEZ RAMOS', administrador:'ANDREA ANTUANETT QUISPE NICOLAS', telTienda:'', celAdmin:'933050759', correo:'to6@footloose.pe' },
  { codigo:'TO7', formato:'R18', nombreCc:'CC Real Plaza Puruchuco', direccion:'Av. Nicolas Ayllon 4770 - LC-206 PURUCHUCO', distrito:'Ate Vitarte', provincia:'Lima', ubicacion:'Lima', cluster:'C', proveedor:'GTD', tipoConexion:'FIBRA ÓPTICA', cid:'NC227157', contingencia:'SI', costo:'650', instruccion:INS_GTD, supervisor:'JORGE JHONATAN VASQUEZ RAMOS', administrador:'FERNANDO LUIS ORIHUELA CACHIQUE', telTienda:'', celAdmin:'989594752', correo:'to7@footloose.pe' },
  { codigo:'TO8', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Centro Cívico 002209, Urb. Centro Cívico, Pariñas', distrito:'Pariñas', provincia:'Talara', ubicacion:'Piura', cluster:'C', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'409', instruccion:INS_CONV, supervisor:'GLADYS MONTALBAN CASTILLO', administrador:'PATRICIA YULETZI FIESTAS YENQUE', telTienda:'', celAdmin:'974039395', correo:'to8@footloose.pe' },
  { codigo:'TO9', formato:'R18', nombreCc:'CC Mega Plaza Chorrillos', direccion:'Av. Alameda Sur esq. con Av. San Marcos, Manzana II, L206-207', distrito:'Chorrillos', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'CLARO', tipoConexion:'LTE', cid:'986707525', contingencia:'', costo:'143.2', instruccion:INS_CLARO, supervisor:'EDITH JOHANNA ESCALANTE RAMOS', administrador:'RENATO PEDRO JOSE CESPEDES CASTILLO', telTienda:'', celAdmin:'905451795', correo:'to9@footloose.pe' },
  { codigo:'TP1', formato:'FOOTLOOSE', nombreCc:'CC Plaza Center', direccion:'Av. Salaverry 888, Tarapoto 22201, LC 105-106', distrito:'Tarapoto', provincia:'San Martin', ubicacion:'Provincia', cluster:'D', proveedor:'GTD', tipoConexion:'FIBRA ÓPTICA', cid:'NC227207', contingencia:'SI', costo:'650', instruccion:INS_GTD, supervisor:'DIEGO JHONATAN SILVA MORI', administrador:'KATERINE ALAVA VELASQUEZ', telTienda:'', celAdmin:'989114758', correo:'TP1@fooloose.pe' },
  { codigo:'TP2', formato:'R18', nombreCc:'Puerta Calle', direccion:'Av. Muro N° 104 Mz. J-1, Lt. 1-F, San Juan de Lurigancho', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'409', instruccion:INS_CONV, supervisor:'ALEX EUSEBIO POVES ZUBIETA', administrador:'KATERIN ARIANA TOLENTINO ROSAS', telTienda:'', celAdmin:'994717252', correo:'tp2@footloose.pe' },
  { codigo:'TP3', formato:'R18', nombreCc:'CC Mega Plaza Barranca', direccion:'Jr. Ramon Zavala N° 164-180 y Jr. Castilla N° 107, interior L-2', distrito:'Barranca', provincia:'Barranca', ubicacion:'Provincia', cluster:'C', proveedor:'CLARO', tipoConexion:'LTE', cid:'', contingencia:'', costo:'76', instruccion:INS_CLARO, supervisor:'JUAN VICTOR PACHERRES PAIVA', administrador:'CATHERYN LUZ CERNA LLANQUE', telTienda:'', celAdmin:'987954430', correo:'TP3@fooloose.pe' },
  { codigo:'TP4', formato:'FOOTLOOSE', nombreCc:'CC Portal F Pizarro', direccion:'Jr. Pizarro No 650-654-664-666, interior LC 203Y204', distrito:'Trujillo', provincia:'Trujillo', ubicacion:'Provincia', cluster:'B', proveedor:'GTD', tipoConexion:'FIBRA ÓPTICA', cid:'NC227118', contingencia:'SI', costo:'650', instruccion:INS_GTD, supervisor:'JUAN VICTOR PACHERRES PAIVA', administrador:'JORGE ANTONIO NEIRA LOZANO', telTienda:'', celAdmin:'966492752', correo:'TP4@fooloose.pe' },
  { codigo:'TP5', formato:'FOOTLOOSE', nombreCc:'CC Mall Aventura', direccion:'Av. Porongoche No. 500, Int. A-1105, Paucarpata', distrito:'Arequipa', provincia:'Arequipa', ubicacion:'Provincia', cluster:'B', proveedor:'ENTEL', tipoConexion:'LTE', cid:'', contingencia:'', costo:'89.7', instruccion:INS_ENTEL, supervisor:'CARLOS RICARDO OPORTO MANSILLA', administrador:'ANA CAROLINA ZAPATA BAUTISTA', telTienda:'', celAdmin:'966492200', correo:'TP5@fooloose.pe' },
  { codigo:'TP6', formato:'FOOTLOOSE', nombreCc:'CC Real Plaza', direccion:'Av. Ejercito No. 1009, interior LC 133, Cayma', distrito:'Cayma', provincia:'Arequipa', ubicacion:'Provincia', cluster:'D', proveedor:'ENTEL', tipoConexion:'LTE', cid:'955451063', contingencia:'', costo:'132', instruccion:INS_ENTEL, supervisor:'CARLOS RICARDO OPORTO MANSILLA', administrador:'CARLOS ALBERTO LIMA NUÑEZ', telTienda:'933047431', celAdmin:'', correo:'TP6@fooloose.pe' },
  { codigo:'TP7', formato:'R18', nombreCc:'Puerta Calle', direccion:'Av. Próceres de la Independencia 1715, San Juan de Lurigancho', distrito:'San Juan de Lurigancho', provincia:'Lima', ubicacion:'Lima', cluster:'D', proveedor:'CONVERGIA', tipoConexion:'FTTH', cid:'ID-TIENDA', contingencia:'', costo:'409', instruccion:INS_CONV, supervisor:'ALEX EUSEBIO POVES ZUBIETA', administrador:'MARIA DEL PILAR CHAVEZ VILLANUEVA', telTienda:'', celAdmin:'970135969', correo:'TP7@fooloose.pe' },
  { codigo:'TP8', formato:'FOOTLOOSE', nombreCc:'Puerta Calle', direccion:'Jr. 28 de Julio Nro. 200-202 Sector Cercado Ayacucho', distrito:'Ayacucho', provincia:'Ayacucho', ubicacion:'Provincia', cluster:'B', proveedor:'', tipoConexion:'', cid:'', contingencia:'', costo:'', instruccion:'', supervisor:'JESLIA MICHEL AVILA ASIPALI', administrador:'ROXANA INGA CURASMA', telTienda:'', celAdmin:'970699461', correo:'TP8@fooloose.pe' },
  { codigo:'TP9', formato:'FOOTLOOSE', nombreCc:'CC Real Plaza Piura', direccion:'Zona Industrial antigua Av. Sánchez Cerro Nro 234, lote A. Local R-04-4', distrito:'Piura', provincia:'Piura', ubicacion:'Provincia', cluster:'', proveedor:'CONVERGIA', tipoConexion:'LTE', cid:'ID-TIENDA', contingencia:'', costo:'380', instruccion:INS_CONV, supervisor:'', administrador:'', telTienda:'', celAdmin:'', correo:'' },
]

const PROV_MAP: Record<string, string> = {
  'FIBRA AMAZONICA': 'FIBRA AMAZÓNICA',
}

async function run() {
  const provRows = await db.select({ id: schema.proveedores.id, nombre: schema.proveedores.nombre }).from(schema.proveedores)
  const provById: Record<string, string> = {}
  for (const p of provRows) provById[p.nombre] = p.id

  function getProvId(nombre: string): string | null {
    if (!nombre) return null
    return provById[PROV_MAP[nombre] ?? nombre] ?? null
  }

  let ok = 0
  for (const t of TIENDAS) {
    const cluster = ['A','B','C','D'].includes(t.cluster) ? t.cluster as 'A'|'B'|'C'|'D' : null
    const vals = {
      codigo:               t.codigo,
      nombreCc:             t.nombreCc || null,
      formato:              t.formato || null,
      direccion:            t.direccion || null,
      distrito:             t.distrito || null,
      provincia:            t.provincia || null,
      ubicacion:            t.ubicacion || null,
      cluster,
      proveedorId:          getProvId(t.proveedor),
      tipoConexion:         t.tipoConexion || null,
      cidServicio:          t.cid || null,
      tieneContingencia:    t.contingencia === 'SI',
      costoMensual:         t.costo || null,
      instruccionReporte:   t.instruccion || null,
      supervisorNombre:     t.supervisor || null,
      administradorNombre:  t.administrador || null,
      contactoSoporte:      t.telTienda || null,
      administradorCelular: t.celAdmin || null,
      administradorEmail:   t.correo || null,
    }
    await db.insert(schema.tiendas).values(vals)
      .onConflictDoUpdate({
        target: schema.tiendas.codigo,
        set: {
          nombreCc:             vals.nombreCc,
          formato:              vals.formato,
          direccion:            vals.direccion,
          distrito:             vals.distrito,
          provincia:            vals.provincia,
          ubicacion:            vals.ubicacion,
          cluster:              vals.cluster,
          proveedorId:          vals.proveedorId,
          tipoConexion:         vals.tipoConexion,
          cidServicio:          vals.cidServicio,
          tieneContingencia:    vals.tieneContingencia,
          costoMensual:         vals.costoMensual,
          instruccionReporte:   vals.instruccionReporte,
          supervisorNombre:     vals.supervisorNombre,
          administradorNombre:  vals.administradorNombre,
          contactoSoporte:      vals.contactoSoporte,
          administradorCelular: vals.administradorCelular,
          administradorEmail:   vals.administradorEmail,
        },
      })
    ok++
    process.stdout.write('.')
  }
  console.log(`\n✓ ${ok} tiendas actualizadas/insertadas`)
  await client.end()
}

run().catch(e => { console.error(e); process.exit(1) })
