const TODOS_LOS_PERMISOS = [
  'incidentes.ver', 'incidentes.crear', 'incidentes.reabrir', 'incidentes.editar', 'incidentes.eliminar', 'incidentes.cancelar',
  'incidentes.editar-tramos',
  'escalamientos.crear',
  'mantenimiento.ver', 'mantenimiento.editar', 'mantenimiento.agregar', 'mantenimiento.eliminar',
  'proveedores.ver', 'proveedores.editar',
  'dashboard.ver', 'reportes.ver',
  'gestion-cambios.ver', 'gestion-cambios.crear', 'gestion-cambios.aprobar',
  'usuarios.ver', 'usuarios.editar', 'usuarios.crear',
  'grupos.gestionar',
]

export const PERMISOS_POR_ROL: Record<string, string[]> = {
  AGENTE: [
    'incidentes.ver', 'incidentes.crear', 'incidentes.reabrir', 'incidentes.editar', 'incidentes.cancelar',
    'escalamientos.crear',
    'dashboard.ver',
    'mantenimiento.ver',
    'proveedores.ver',
    'grupos.gestionar',
  ],
  INFRAESTRUCTURA: [
    'incidentes.ver', 'incidentes.crear', 'incidentes.reabrir', 'incidentes.editar', 'incidentes.cancelar',
    'escalamientos.crear',
    'mantenimiento.ver', 'mantenimiento.editar', 'mantenimiento.agregar',
    'dashboard.ver', 'reportes.ver',
    'proveedores.ver', 'proveedores.editar',
    'gestion-cambios.ver', 'gestion-cambios.crear',
    'usuarios.ver',
    'grupos.gestionar',
  ],
  SUPERVISOR: [
    'incidentes.ver', 'incidentes.crear', 'incidentes.reabrir',
    'incidentes.editar', 'incidentes.eliminar', 'incidentes.cancelar',
    'incidentes.editar-tramos',
    'escalamientos.crear',
    'mantenimiento.ver', 'mantenimiento.editar', 'mantenimiento.agregar', 'mantenimiento.eliminar',
    'dashboard.ver', 'reportes.ver',
    'usuarios.ver', 'usuarios.editar', 'usuarios.crear',
    'proveedores.ver', 'proveedores.editar',
    'gestion-cambios.ver', 'gestion-cambios.crear', 'gestion-cambios.aprobar',
    'grupos.gestionar',
  ],
  GERENCIA: [
    'incidentes.ver',
    'dashboard.ver', 'reportes.ver',
    'mantenimiento.ver',
    'proveedores.ver',
    'usuarios.ver',
    'gestion-cambios.ver', 'gestion-cambios.aprobar',
  ],
  DEMO: TODOS_LOS_PERMISOS,
}
