export const PERMISOS_POR_ROL: Record<string, string[]> = {
  AGENTE: [
    'incidentes.ver', 'incidentes.crear', 'incidentes.reabrir',
    'escalamientos.crear', 'escalamientos.envio', 'escalamientos.respuesta',
    'dashboard.ver',
    'mantenimiento.ver',
    'proveedores.ver',
  ],
  INFRAESTRUCTURA: [
    'incidentes.ver', 'incidentes.crear', 'incidentes.reabrir',
    'escalamientos.crear', 'escalamientos.envio', 'escalamientos.respuesta',
    'mantenimiento.ver', 'mantenimiento.editar', 'mantenimiento.agregar',
    'dashboard.ver', 'reportes.ver', 'reportes.exportar',
    'proveedores.ver', 'proveedores.editar',
    'decisiones.ver', 'decisiones.crear',
  ],
  SUPERVISOR: [
    'incidentes.ver', 'incidentes.crear', 'incidentes.reabrir',
    'incidentes.editar', 'incidentes.eliminar',
    'escalamientos.crear', 'escalamientos.envio', 'escalamientos.respuesta',
    'mantenimiento.ver', 'mantenimiento.editar', 'mantenimiento.agregar',
    'dashboard.ver', 'reportes.ver', 'reportes.exportar',
    'usuarios.ver', 'usuarios.editar', 'usuarios.crear',
    'proveedores.ver', 'proveedores.editar',
    'decisiones.ver', 'decisiones.crear',
  ],
  GERENCIA: [
    'incidentes.ver',
    'dashboard.ver', 'reportes.ver', 'reportes.exportar',
    'mantenimiento.ver',
    'proveedores.ver',
    'usuarios.ver',
    'decisiones.ver', 'decisiones.crear',
  ],
}
